### ISSUE TITLE
Maven Plugin for generating AsyncApi specification during build

### ISSUE THREAD

**Issue by murdos** [springwolf/springwolf-core#1024]
**Describe the feature request**
A maven plugin that would generates the AsyncApi contract (either in json or yaml) during build, with the ability to attach the generated contract to the artifacts published.

**Motivation**
Generates and automatically publish the contract for consumption by partnership applications.
Ease contract testing, e.g. using [Microcks](https://microcks.io/)

**Technical details**
Ideally generates the contract without having to start the application, as done for OpenApi by https://github.com/kbuntrock/openapi-maven-plugin/.
If not possible, something similar to https://github.com/springdoc/springdoc-openapi-maven-plugin

**Comment by sam0r040** [comment]
Hi @murdos,
can you use the springdoc-openapi-maven-plugin with Springwolf like it can be done with the springdoc-openapi-gradle-plugin? See https://www.springwolf.dev/docs/faq#how-to-generate-the-documentation-at-build-time for more information.
As you said, the plugin is basically starting the application and downloading the spec from a given endpoint. Therefore I would expect that the maven plugin is similar, or is there something different?

**Comment by murdos** [comment]
Hi, I had not read the FAQ before, so I was not aware of this solution!
I think we can then close the issue (I would love to have a plugin that doesn't require you to start the application, but I guess it's incompatible with the current design of springwolf).
