### ISSUE TITLE
Example amqp project not showing any data

### ISSUE THREAD

**Issue by MikhailYarochkin** [springwolf/springwolf-core#103]
I am trying to run springwolf-amqp-example.

When I sun docker-compose I see an example UI. 
![image](https://user-images.githubusercontent.com/95617105/197163763-ce11b7f2-7cab-42cc-a228-43d564085c88.png)

And when i run the example locally (IntelliJ, no changes in code) with RabbitMQ from the docker-compose file, the UI page is empty
![image](https://user-images.githubusercontent.com/95617105/197162391-f1f938d7-b4e3-4acb-80e4-5b4fd6dd1e1a.png)

What I am doing wrong?

**Comment by stavshamir** [comment]
You're not doing anything wrong - we changed the backend endpoint so the latest released version of the UI doesn't work with it anymore. 

It will be fixed in the next release of the UI. If you want to see it running now, checkout the latest springwolf-core release tag instead of the master branch.

**Comment by MikhailYarochkin** [comment]
Nice to hear this.
Any projection about the release time of the new frontend?

**Comment by stavshamir** [comment]
Next few days

**Comment by MikhailYarochkin** [comment]
How i can see it is released?

**Comment by stavshamir** [comment]
It will be available tomorrow morning. You can check the Releases section in this repo or the UI repo, and I will also announce it the the discord server, you can join here if you'd like https://discord.gg/HZYqd5RPTd
