### ISSUE TITLE
Springwolf spring-cloud-stream should support BiConsumer

### ISSUE THREAD

**Issue by LeovR** [springwolf/springwolf-core#1071]
**Describe the feature request**
With Spring Cloud Stream one is able, in addition to `Function` and `Consumer`-Beans to use `BiFunction` or `BiConsumer`-Beans.
E.g. with a Kafka-Binder, a `BiConsumer` can be used to also consume the Kafka-Headers.
Currently, only `Consumer`, `Function` or `Supplier` can be used.

In addition, the `DefaultBeanMethodsScanner` should also consider all `@Component`-Beans and not just bean-methods in `@Configuration`-classes because those can also be provided via other `@Component`-annotations.

**Motivation**
We're relying on `BiConsumer` to consume headers.

**Technical details**
It should be considered, whether the Spring `FunctionCatalog` could be used to get a hold of the function-bindings, since all the scanned functions are already registered in the catalog.

**Comment by timonback** [comment]
Hello @LeovR ,
that is a great addition.

Do you have a code example for the usage with headers? (Can be added to the cloudstream example later)
In the docs, I found a section where messages from two different topic are consumed: https://docs.spring.io/spring-cloud-stream/reference/kafka/kafka-streams-binder/programming-model.html#multiple-input-bindings

**Comment by LeovR** [comment]
Hi @timonback,

unfortunately this feature is not documented very well.
The link you provided is about the Kafka Streams binding and not the "normal" Kafka binding.

I will pick this up myself then and create a pull request when I'm done.

At least I wanted to make sure whether this is wanted.

**Comment by timonback** [comment]
Thank you @LeovR for adding the functionality of `BiConsumer`, it is already visible on the demo website [0] and about to be part of the `-SNAPSHOT` artifacts.

Do you plan to continue on i.e. BiFunction, FunctionCatalog, native cloudstream publishing?
If not, I will mark this issue as completed (you can always re-open/create a new one)

[0] https://cloud-stream.demo.springwolf.dev/springwolf-ui/asyncapi-ui.html#channel-biconsumer-topic

**Comment by LeovR** [comment]
@timonback 
Maybe we should close this one and I will create new issues for the other parts.
I don't know yet when I will be able to do those.
