### ISSUE TITLE
Disabling springwolf breaks application

### ISSUE THREAD

**Issue by nwwerum** [springwolf/springwolf-core#1073]
**Describe the bug**
When setting springwolf.enabled=false spring boot application with springwolf generic binding will not start anymore.

**Dependencies and versions used**
1.8, including springwolf.generic.binding

**Code example**
Include generic binding jar in the classpath of a spring boot app and set springwolf.enabled=false 

**Stack trace and error logs**
```
org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncGenericOperationBindingProcessor' defined in class path resource [io/github/springwolf/addons/generic_binding/annotation/configuration/SpringwolfGenericBindingAutoConfiguration.class]: Unsatisfied dependency expressed through method 'asyncGenericOperationBindingProcessor' parameter 0: No qualifying bean of type 'org.springframework.util.StringValueResolver' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

Problem seems to be that SpringwolfGenericBindingAutoConfiguration does not react to the enabled property and will try to create its bean in any case, even if other springwolf beans (in this case `StringValueResolverProxy`) are not created.

An easy solution would be to add a `@ConditionalOnBean(StringValueResolver.class)` to the  `asyncGenericOperationBindingProcessor() ` method.
Edit: other autoconfigs replicate the `@ConditionalOnProperty` (and do not use a  `@ConditionalOnBean`),  so it makes sense to handle this the same way.

**Comment by timonback** [comment]
Awesome, thank you for the contribution!
