### ISSUE TITLE
Maven spring (boot) versions are invalid '<version>.</version>'

### ISSUE THREAD

**Issue by piewie** [springwolf/springwolf-core#1086]
**Describe the bug**
Since 1.8.0 maven pom does not longer has a version for spring (and spring boot) dependencies, see https://repo1.maven.org/maven2/io/github/springwolf/springwolf-core/1.8.0/springwolf-core-1.8.0.pom

Since there is no version specified in either the dependency management nor parent, this results in an error (classes missing or semver compatibility issues). (solution now is exclude them all and specify add the dependencies ourselves)

**Dependencies and versions used**
1.8.0

**Code example**
If possible, an example project or snippet that reproduces the bug.

**Stack trace and error logs**
If an exception has been thrown or an error was logged by springwolf.

example semver
Some nested dependencies use another major version for org.springframework:spring-messaging:6.1.13
paths to dependency are:
+-xx
  +-yy
    +-io.github.springwolf:springwolf-core:1.8.0 (managed) <-- io.github.springwolf:springwolf-core:1.8.0
      +-org.springframework:spring-messaging:6.1.13 [runtime] (managed) <-- org.springframework:spring-messaging:. [runtime]

**Comment by timonback** [comment]
Thank you for the report @piewie!
This is related to the switch to gradle version catalog, which had unforeseen failures for the maven pom files.

I merged #1088 to address it and the spring boot dependencies do not have a version anymore (in 1.8.0 they used `.`).

Pom files for `springwolf-core` related to the merge of the PR #1088:
before: https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/springwolf/springwolf-core/1.9.0-SNAPSHOT/springwolf-core-1.9.0-20241118.163136-30.pom
After: https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/springwolf/springwolf-core/1.9.0-SNAPSHOT/springwolf-core-1.9.0-20241120.190409-31.pom

Can you verify the 1.9.0-SNAPSHOT version to confirm it is working for you again?

**Comment by piewie** [comment]
@timonback according to my colleague it's fixed indeed, thx for the quick work.
What's your release schedule, each month?

**Comment by timonback** [comment]
Yes, we plan for Friday next week.
