### ISSUE TITLE
Enable SpringwolfKafkaProducer configuration from the user

### ISSUE THREAD

**Issue by stavshamir** [springwolf/springwolf-core#126]

**Comment by sam0r040** [comment]
Do I understand it correctly, that it should be possible to configure https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/kafka/KafkaProperties.Producer.html in the application configuration to give full control over the KafkaTemplate (independent of what was or was not configured as part if the spring configuration)?

**Comment by sam0r040** [comment]
@stavshamir I started working with my interpretation of the feature and added #144 as a proposal

**Comment by timonback** [comment]
The new version of springwolf has been released. Thank you @sam0r040 for the contribution
