### ISSUE TITLE
Quarkus Support

### ISSUE THREAD

**Issue by t-riegel** [springwolf/springwolf-core#158]
Hi everyone,

we are using Quarkus and AMQP for the async communication in our project. We are looking for a possibility to automatically generate a documentation for our async communication.

Are you planning to add support for Quarkus?

**Comment by Pakisan** [comment]
@t-riegel hi!

You can check out project from these folks - https://github.com/quarkiverse/quarkus-asyncapi

**Comment by t-riegel** [comment]
Hi @Pakisan, thanks for the hint! Appreciated!

**Comment by timonback** [comment]
Hi @t-riegel,

Thank you for the suggestion.

At the moment, Springwolf is focused on the spring ecosystem.
Adding support for frameworks next to Spring is currently not part of the roadmap.

I hope that the `quarkus-asyncapi` project provides what you are looking for.
