### ISSUE TITLE
'exampleSetFlag' value from Swagger-Core is leaked into the JSON serialized specification

### ISSUE THREAD

**Issue by ctasada** [springwolf/springwolf-core#169]
**Describe the bug**
When creating the `asyncapi.json` file it contains properties that do not belong to the AsyncAPI specification, but that are swagger-core internals.

Unexpected values
* exampleSetFlag
* types[]

A similar issue is reported at https://github.com/swagger-api/swagger-core/pull/3637#issuecomment-682370287

**Dependencies and versions used**
`springwolf-core` version `0.10.0`.

**Code example**
Serialized value
```json
          "bindings" : {
            "kafka" : {
              "key" : {
                "type" : "string",
                "exampleSetFlag" : false,
                "types" : [ "string" ]
              },
              "bindingVersion" : "binding-version-1"
            }
          }
```
Expected value
```json
          "bindings" : {
            "kafka" : {
              "key" : {
                "type" : "string"
              },
              "bindingVersion" : "binding-version-1"
            }
          }
```

**Comment by timonback** [comment]
Re-opening as the underlying issue is not solved.
Relates to: https://github.com/springwolf/springwolf-core/issues/160

**Comment by ctasada** [comment]
@timonback this specific issue should be now fixed
