### ISSUE TITLE
JMS support for Spring wolf. 

### ISSUE THREAD

**Issue by sajeeshkumar** [springwolf/springwolf-core#173]
Many organization use JMS protocol to interface with message queues brokers like IBM WMB, Apache ActiveMQ or Artemis, Tibco etc.

**Comment by sajeeshkumar** [comment]
RabbitMQ supports AMQP protocol.

There is another protocol JMS https://www.oracle.com/java/technologies/java-message-service.html

It is used heavily in the Java world. Spring has a listener annotation for it called as JMSListener on the lines of RabbitListener or KafkaListener

**Comment by timonback** [comment]
I see. You are interested in the auto-detection of methods annotated with the JmsListener annotation.

Springwolf uses plugins ([more details here](https://springwolf.github.io/docs/behind-the-scenes#plugins)) to scan for protocol specific annotations.
Although Jms is not a protocol, but rather an API, I can imagine it to be an own springwolf plugin.

In case anyone wants to get started on it (plugin + example project), feel free to. We are happy to assist.

To provide details about the protocol in use (`anypointmq`, `ibmmq`, `jms` are documented/mentioned in the [asyncapi spec](https://www.asyncapi.com/docs/reference/specification/v2.6.0#operationBindingsObject)) via an custom annotation, a look at
[KafkaAsyncOperationBinding](springwolf-plugins/springwolf-kafka-plugin/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/operationdata/annotation/KafkaAsyncOperationBinding.java) might be helpful.

**Comment by timonback** [comment]
Thank you for the report, the issue has been addressed in the new release with the jms plugin.

Feel free to reopen this issue if there is still something missing.
