### ISSUE TITLE
Feature/Question:  Possible to perform directModelSubstitute?

### ISSUE THREAD

**Issue by buyukim** [springwolf/springwolf-core#175]
**Describe the feature request**
Would like the ability to perform model/schema type search and replacement of classes at runtime, similar to how we used `directModelSubstitute` with the SpringFox library.  

**Motivation**
We are trying to leverage [CloudEvents](https://cloudevents.io) that wrap around our model classes when being published, but I do not think there is an easy way to automatically detect and perform this replacement, as their CloudEvent API does not really support Generics.

I would like to avoid having everyone put redundant annotations on publishing methods, re-iterating what the code is already doing.  This has a tendency to yield copy+paste errors adds clutter.

**Technical details**
Add `directModelSubstitute` to the AsyncApiDocket Builder.

**Describe alternatives you've considered**
Alternatively, could there be some way to perform post-processing __after__ SpringWolf has done its thing with the Docket...but __before__ it gets finalized/sent back to the SpringWolf Web UI / raw contract endpoints?

**Comment by buyukim** [comment]
I think the current plan was to do the opposite, we can auto-detect the 'data' classes being published, but we need to auto-wrap cloudevent spec around them:
```
components/schema/EventType1
- myattribute1
- myattritute2
---
components/schema/CloudEventType1
- id
- contenttype
- . . . (other cloudevent spec fields)
- data
  - type: object
  - properties:
    - myattriibute1
    - myattribute2 
```
1.) I was thinking about trying to create a separate CloudEvent type that supports generics, but I am not sure if that will work.  I remember having issues with Springwolf a couple years back with the older java v1 CloudEvent type that did support generics for the 'data' class, but was not able to generate proper contracts (i.e., only generated the wrapper, not the data class).  
     It is a hack, but I was thinking about using ByteBuddy to piece together the impl classes at runtime for the purposes of Springwolf/AsyncAPI contract

2.) We could ditch the Java CloudEvent SDK and use our own CloudEvent parent class, which can use simple class inheritance (i.e., parent class respects the CloudEvent spec EXCEPT for 'data', which subclasses will specify)

**Comment by buyukim** [comment]
Another, more generic, alternative would be to create a functional interface for global AsyncAPI object customizers, similar to [springdoc-openapi](https://github.com/springdoc/springdoc-openapi/blob/v2.1.0/springdoc-openapi-starter-common/src/main/java/org/springdoc/core/customizers/OpenApiCustomizer.java):
```

@FunctionalInterface
public interface AsyncApiCustomizer {

	/**
	 * Customize.
	 *
	 * @param asyncApi the async api contract
	 */
	void customize(AsyncAPI asyncApi);

}


@Configuration
public class AsyncApiConfig {
  @Bean
  public AsyncApiCustomizer myAsyncApiCustomizer() {
      return asyncApi ->
           asyncApi....;
  }
}
```

**Comment by timonback** [comment]
I like this customizer approach as well as it is generic and allows users to adapt the document to their liking. (Customizer is only one approach, others are fine as well)

If you (or anyone else) like to start on it, go ahead.
We are happy to help via this issue or discord.

**Comment by timonback** [comment]
Thank you for the suggestion.
The suggested customizer approach has been implemented in https://github.com/springwolf/springwolf-core/pull/265

It will be part of the next release. Note that it is a low-level way to interact with springwolf as described in the interface's comment.

**Comment by timonback** [comment]
This issue has been addressed in the new release.

Feel free to reopen this issue if there is still something missing.
