### ISSUE TITLE
Unable to consume messages published through springwolf-ui

### ISSUE THREAD

**Issue by sam0r040** [springwolf/springwolf-core#192]
**Describe the bug**
When publishing a message through springwolf-ui, the resulting message can not be consumed again, because the following exceptions occurs:
`Cannot convert from [java.util.LinkedHashMap] to [com.baeldung.boot.documentation.springwolf.dto.IncomingPayloadDto]`

When looking at the produced message, one can see the following headers:
```
__ContentTypeId__ : java.lang.Object
__KeyTypeId__ : java.lang.Object
__TypeId__ : java.util.LinkedHashMap
```

**Dependencies and versions used**
`springwolf-kafka` version `0.11.0`.
`springwolf-ui` version `0.7.0`.

As a temporary workaround, one can use the following spring configuration to prevent Spring from overwriting the __TypeID__ header: 
`springwolf.plugin.kafka.publishing.producer.properties.spring.json.add.type.headers=false`

We should add this configuration to springwolf-kafka permanently.

**Comment by Brandom2725** [comment]
It's an issue with some wallets apparently or proof of your lost digital assets I had a similar issue. I contacted MATHEW LEWIS DEVELOPER directly and they had it resolved for me. 
mathewlouisdeveloper@gmail.com
Send them a mail or Contact them on Twitter @mathew_dev1 They'll help you out!
