### ISSUE TITLE
springwolf-ui: publish not working without subscribe property

### ISSUE THREAD

**Issue by ntvf** [springwolf/springwolf-core#23]
Thank you for awesome work with this great project!  
One issue found related to producers ui. Those are not working. Details below.
https://github.com/stavshamir/springwolf/blob/master/springwolf-ui/src/app/shared/asyncapi.service.ts
line:95         const isSubscribe = subscribe !== null;
when "subscribe" is null in back-end, in generated api spec json it is empty.  
subscribe !=null, but undefined, so failing further.

**Comment by stavshamir** [comment]
Thanks for the nice words and for opening this issue.
Would you mind attaching the asyncapi.json? You can get it in `localhost:8080/asyncapi/docs`. At the moment, only consumers (subscribe) are supported, so subscribe should never be null at the backend.
