### ISSUE TITLE
Discussion: Versioning strategy

### ISSUE THREAD

**Issue by timonback** [springwolf/springwolf-core#258]
As we have moved to a mono repo now, I believe we can simplify the versioning strategy so that during a release, all artifacts will have the same version.

So, for an upcoming release, `springwolf-core`, `springwolf-amqp`, ..., `springwolf-ui` will all be released as i.e. `0.13.0`.
As a consequence, for some artifacts versions will be skipped to catch up (i.e. `springwolf-cloud-stream` will jump from `0.3.0` to `0.13.0`

This should simplify the release process, but especially make it easier for users to know which versions work together.

---

Related, we want to be conform to the standard version lifecycle when using SNAPSHOT versions (as suggested in https://github.com/springwolf/springwolf-core/pull/245#issuecomment-1609004256)
Instead of release version `0.13.0` and the continuing to push updates on master to `0.13.0-SNAPSHOT`, we want to release `0.13.0` and right after start pushing to `0.14.0-SNAPSHOT` until `0.14.0` is getting released.

---

Any thoughts/suggestions on this?

**Comment by ctasada** [comment]
I really like the idea 😄

**Comment by stavshamir** [comment]
I like this idea as well, will simplify things a lot.

**Comment by timonback** [comment]
Thank you for the feedback. 

The proposal has been accepted.
The next version is going to be 0.13.0 for all dependencies. Snapshots version of 0.13.0 are being build today.
