### ISSUE TITLE
RabbitMQ Support

### ISSUE THREAD

**Issue by shkup** [springwolf/springwolf-core#26]
I have an already existing `spring boot` application that listens to `RabbitMQ` queue. It consumes a specific message (wrapped in `CloudEvent`) under specific topic. Can this generator assist me in exposing it as AsyncApi?  Does it respect `CloudEvent` object?

**Comment by stavshamir** [comment]
Opened a new project for rabbit, thanks for the contribution.

**Comment by stavshamir** [comment]
Rabbitmq support has been added.
