### ISSUE TITLE
Cannot handle multiple group-ids with same topic when @KafkaListener on method level

### ISSUE THREAD

**Issue by setarator** [springwolf/springwolf-core#278]
**Describe the bug**
When there are multiple consumers consuming the same topic with different group-id annotated with @KafkaListener on method level, MethodLevelKafkaListenerScanner throws an exception while scanning due to duplicate key of topics. This issue looks like the same as previously fixed https://github.com/springwolf/springwolf-core/issues/85

**Dependencies and versions used**
`springwolf-kafka` version `0.11.0`.

**Stack trace and error logs**
`2023-07-06T11:41:08.970Z ERROR 1 --- [           main] i.g.s.s.asyncapi.DefaultChannelsService  : An error was encountered during channel scanning with io.github.stavshamir.springwolf.asyncapi.scanners.channels.annotation.MethodLevelKafkaListenerScanner@7a247711: Duplicate key example.topic ...`

Above error is thrown here https://github.com/springwolf/springwolf-core/blob/master/springwolf-core/src/main/java/io/github/stavshamir/springwolf/asyncapi/scanners/channels/annotation/AbstractMethodLevelListenerScanner.java#L44

**Comment by timonback** [comment]
Thank you @setarator for the report.

Springwolf support for multiple servers/listeners with the exact same topic + payload is currently limited, but it is one of the things we are working on.

The linked PR resolves the exception https://github.com/springwolf/springwolf-core/pull/289, however only one group-id will be documented - not both.

You or anyone else is welcome to improve and contribute an improved logic to run the ChannelMerge earlier and take care of merging protocol specific attributes (i.e. group-id)

**Comment by timonback** [comment]
The change has been merged and will be part of the next release.

If you want to try and verify it in your application, use the current `SNAPSHOT` build as described in our [README.md](https://github.com/springwolf/springwolf-core)

Thank you for the report/contribution!

**Comment by timonback** [comment]
Thank your for the report, the issue has been addressed in the new release.

Feel free to reopen this issue if there is still something missing.
