### ISSUE TITLE
UI shows up but does not contain any publish/subscribe channels

### ISSUE THREAD

**Issue by coiouhkc** [springwolf/springwolf-core#286]
**Describe the bug**
Springwolf UI does not contain any channels

**Dependencies and versions used**
`springwolf-kafka` version `0.10.0`, `springwolf-ui` version `0.6.0` .

**Code example**
Based off https://github.com/thepracticaldeveloper/kafka-spring-boot-example + configuration based on https://www.springwolf.dev/docs/quickstart

**Comment by coiouhkc** [comment]
> do you have a more detailed error description, like exception thrown or error message from the browser console/network tab?

Hi @timonback, sorry, i've re-written the initial report a couple of times and forgot to include the essential information in the final version. 

Here's the error from the console (HTTP 404 for springwolf/docs):

```
ERROR 
Object { headers: {…}, status: 404, statusText: "OK", url: "http://localhost:8080/springwolf/docs", ok: false, name: "HttpErrorResponse", message: "Http failure response for http://localhost:8080/springwolf/docs: 404 OK", error: {…} }
main-es2015.f2cdf53117163d7cda62.js:1:49783
```

**Comment by coiouhkc** [comment]
See https://github.com/coiouhkc/springwolf-286

**Comment by timonback** [comment]
Hi @coiouhkc,

I had a look and changed some things: https://github.com/coiouhkc/springwolf-286/pull/1

Please have a look at our kafka example project, which includes a running example and go from there and adapt it to your needs (consumer factories, etc).

As part of knowledge sharing, here is what I found:
- Update to the latest springwolf and spring boot version
  - Related: In older springwolf versions the `@EnableAsyncApi` annotation was needed
- When specifying configuration in the application.properties and as a `@Configuration` docket, only the application.properties setting is used. -> therefore the file was removed
- To document the listeners, the annotation approach is used. Same can be done for the producers

**Comment by timonback** [comment]
We will update the documentation to better reflect the new way to document listeners/publishers in https://github.com/springwolf/springwolf.github.io/pull/45
