### ISSUE TITLE
replace componentscan based context configuration with explicit configuration file and @Beans declarations

### ISSUE THREAD

**Issue by tvahrst** [springwolf/springwolf-core#291]
Currently all Spring beans for springwolf-core as well as for all plugins are detected by spring's componentscan mechanism (plugin beans centrally scanned by springwolf-core configuration) . I suggest to change this to instead provide spring configuration files with explicit @Beans declaration of all necessary beans. 

**Motivation**
First of all, by providing explicit @Bean declarations it becomes much more transparent, which beans (classes) are part of the core/plugin functionality. 
Secondly, an explicit configuration allows springboot conditionals like @ConditionalOnBean or @ConditionalOnProperty. This is a well known pattern in springboot starters to allow application code to hook into the core/plugin logic. 

Moreover, explicit bean declarations comes with a performance gain compared to component scan. All springboot autoconfigurations and starter moduls I am knowing of are using @Bean configuration files.

**Technical details**
springwolf-core as well as all plugins provide their own spring autoconfiguration classes. These (auto)configuration classes will contain all necessary beans as @Bean declarations.

**Comment by Brandom2725** [comment]
It's an issue with some wallets apparently or proof of your lost digital assets I had a similar issue. I contacted MATHEW LEWIS DEVELOPER directly and they had it resolved for me. 
mathewlouisdeveloper@gmail.com
Send them a mail or Contact them on Twitter @mathew_dev1 They'll help you out!
