### ISSUE TITLE
Cloud not run docker compose up on spring-cloud-stream-example

### ISSUE THREAD

**Issue by nguyenminhtuanfit** [springwolf/springwolf-core#295]
Error response from daemon: manifest for stavshamir/springwolf-cloud-stream-example:0.13.0 not found: manifest unknown: manifest unknown

**Comment by sam0r040** [comment]
Hi, we have not published version 0.13.0 of the cloud stream example yet. You can either use the snapshot or an older version. You can see the published versions here: https://hub.docker.com/r/stavshamir/springwolf-cloud-stream-example/tags

**Comment by timonback** [comment]
Thank your for the report, 0.13.0 has been released and we have improved the project to avoid confusions like these in the future.

Feel free to reopen this issue if there is still something missing.
