### ISSUE TITLE
Enhancing KafkaOperationBinding

### ISSUE THREAD

**Issue by chris0550** [springwolf/springwolf-core#30]
Hello,
maybe it would bring a benefit if we change the `GroupId groupId` to a more generic type in order to fulfill also other [requirements](https://github.com/asyncapi/bindings/blob/master/kafka/README.md#message) like the clientId.

https://github.com/springwolf/springwolf-core/blob/e139fa12189494cc384bf63d717d16ba988ba19d/src/main/java/io/github/stavshamir/springwolf/asyncapi/types/channel/operation/bindings/kafka/KafkaOperationBinding.java#L20

What do you think about it?

Greetings
Chris

**Comment by stavshamir** [comment]
Hi @chris0550, there is another library that implements the entire asyncapi spec for java which I intend to switch to in the future. In the meanwhile if there are some missing fields which are important to you, feel free to provide a PR with the desired changes, your other PRs were very valuable!

**Comment by stavshamir** [comment]
Now when #33 , this can be closed.
