### ISSUE TITLE
Configurable docs URL path

### ISSUE THREAD

**Issue by indrekots** [springwolf/springwolf-core#34]
Would it be possible to make the docs path configurable via properties?

Example `application.properties`
```
springwolf.path=/my/docs/path
```

**Comment by stavshamir** [comment]
Do you mean the url path?

**Comment by indrekots** [comment]
Yes, exactly (updated issue title). I'd like to serve the docs from a different path.

**Comment by stavshamir** [comment]
Do you need this feature to work with the UI?

**Comment by indrekots** [comment]
No. I'd only like to configure the URL that produces the JSON output.

**Comment by stavshamir** [comment]
No problem, will be available in the next release :)

**Comment by stavshamir** [comment]
The documentation API endpoint url is now configurable from `application.properties` with the property `springwolf.paths.docs`. Please not that setting this property to any value other than the default will result in the UI not working.

**Comment by rnjesuz** [comment]
@stavshamir Is it possible configure the UI path as well? I would like to serve both json and ui in custom paths. But even if it would default to the ui would be great

**Comment by rnjesuz** [comment]
@stavshamir Is it possible to serve the UI in a costum path? Actually is there any way to serve both json and ui in custom paths, that would be really helpful
