### ISSUE TITLE
Springwolf Kafka Controller Objectmapper Creation

### ISSUE THREAD

**Issue by kaant2** [springwolf/springwolf-core#357]
Hi,

I use protobuf and I configured objectMapper to works with protobufs. When I used springwolf publish button by ui, it gives an error on the line ` Object payload = objectMapper.readValue(message.getPayload(), payloadClass)` in `SpringwolfKafkaController.class`. When I debug, What I found is springwolf creates its own objectMapper. Can you please autowire objectMapper in SpringwolfKafkaController instead of creating a new one?

```
@Slf4j
@RestController
@RequestMapping("/springwolf/kafka")
@RequiredArgsConstructor
@ConditionalOnProperty(prefix = SPRINGWOLF_KAFKA_CONFIG_PREFIX, name = SPRINGWOLF_KAFKA_PLUGIN_PUBLISHING_ENABLED)
public class SpringwolfKafkaController {

    private final AsyncApiDocketService asyncApiDocketService;

    private final SpringwolfKafkaProducer producer;
    private final ObjectMapper objectMapper = new ObjectMapper();

    @PostMapping("/publish")
    public void publish(@RequestParam String topic, @RequestBody MessageDto message) {
        if (!producer.isEnabled()) {
            log.debug("Kafka producer is not enabled - message will not be published");
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Kafka producer is not enabled");
        }

        String payloadType = message.getPayloadType();
        if (payloadType.startsWith(asyncApiDocketService.getAsyncApiDocket().getBasePackage())) {
            try {
                Class<?> payloadClass = Class.forName(payloadType);
                Object payload = objectMapper.readValue(message.getPayload(), payloadClass);

                String kafkaKey =
                        message.getBindings() != null ? message.getBindings().get("key") : null;
                log.debug("Publishing to kafka topic {} with key {}: {}", topic, kafkaKey, message);
                producer.send(topic, kafkaKey, message.getHeaders(), payload);
            } catch (ClassNotFoundException | JsonProcessingException ex) {
                throw new ResponseStatusException(
                        HttpStatus.BAD_REQUEST,
                        MessageFormat.format(
                                "Unable to create payload {0} from data: {1}", payloadType, message.getPayload()));
            }
        } else {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "No payloadType specified.");
        }
    }
}
```

**Comment by stavshamir** [comment]
Hi @kaant2 , this sounds like a good idea, would like to contribute this enhancement? We will be happy to assist if you have any questions.

**Comment by kaannbey** [comment]
Could you authorized this gmail account? When I tried to push, I got this error:

remote: Permission to springwolf/springwolf-core.git denied to kaannbey.
fatal: unable to access 'https://github.com/springwolf/springwolf-core.git/': The requested URL returned error: 403

**Comment by stavshamir** [comment]
Did you fork the repo? You should work on a fork and create a pull request when ready

**Comment by timonback** [comment]
We wrote down a guide at the bottom of https://github.com/springwolf/springwolf-core/blob/master/CONTRIBUTING.md to make contributions as easy as possible.

**Comment by dipeshsingh253** [comment]
Hi @timonback , I think this issue has been resolved: https://github.com/springwolf/springwolf-core/tree/master/springwolf-core/src/main#L37

**Comment by timonback** [comment]
Thank you for the report @kaant2 

A fix has been provided in the latest release.
Feel free to re-open if the issue persists.
