### ISSUE TITLE
:mega: Contributions

### ISSUE THREAD

**Issue by timonback** [springwolf/springwolf-core#371]
Feel free to get started on any issue. We recommend the `good first issue` ones for a start.

Also, our [`springwolf-ui`](https://github.com/springwolf/springwolf-core/tree/master/springwolf-ui) angular application is a good start. Check out the [live demo](https://demo.springwolf.dev/springwolf-ui/asyncapi-ui.html) linked in the [README.md](https://github.com/springwolf/springwolf-core/blob/master/README.md) or dive directly into the code. After `git checkout` just run `npm install & npm start` and start hacking away.

Join us on our [Discord channel](https://discord.gg/HZYqd5RPTd) if you have any questions.
Some questions are already answered in our [CONTRIBUTING.md](https://github.com/springwolf/springwolf-core/blob/master/CONTRIBUTING.md) guide.

**Comment by JayOaks** [comment]
Hi,
The discord invite has expired.
