### ISSUE TITLE
Kafka Topic with Primitive Type Not Displayed in UI

### ISSUE THREAD

**Issue by jenarp** [springwolf/springwolf-core#376]
**Environment:**

Springwolf UI version: 0.14.0
Browser: Chrome 116.0.5845.187
Operating System: macOS Ventura 13.4.1

**Description:**
When utilizing the Springwolf UI to convert an Async API Specification into a user interface, I've noticed that Kafka topics which have only a primitive type (e.g., a simple string) instead of a JSON object are not being shown in the resulting UI.

**Steps to Reproduce:**

- Set up a Kafka topic with a primitive type (e.g., string).
- Use the Springwolf UI to convert the associated Async API Specification.
- Observe that the Kafka topic does not appear in the UI.

**Expected Behavior:**
Kafka topics, regardless of their payload type (primitive or JSON), should be displayed accurately in the Springwolf UI.

**Actual Behavior:**
Kafka topics with primitive types are missing from the rendered UI.

**Additional Details:**

AsyncApi Spec with string as payload:
<img width="1289" alt="Screenshot 2023-09-26 at 11 01 49" src="https://github.com/springwolf/springwolf-core/assets/67540243/3e9ed99b-d9d2-420a-8792-7ae342229af7">

No example visible in UI:
<img width="1376" alt="Screenshot 2023-09-27 at 15 30 57" src="https://github.com/springwolf/springwolf-core/assets/67540243/05d669d1-e4b0-4082-a886-05d36f27f4c0">

**Potential Impact:**
This might lead to an incomplete representation of the Async API Specification, leading users to overlook or miss out on the functionality and details of some Kafka topics.

**Suggested Fix:**
Investigate the Springwolf UI's rendering logic to ensure that Kafka topics with primitive types are included in the UI.

**Comment by stavshamir** [comment]
Hi @jenarp, thanks for the detailed report!

Would you like to contribute a fix? This looks like a good first issue.
If you do, please let us know if you need any guidance.

**Comment by jenarp** [comment]
Hi @stavshamir,

thank you for the opportunity. 🙂 
I'm definitely interested in looking into this and contributing a fix. However, I'd like to set expectations upfront: while I'm eager to tackle the problem, I can't guarantee a specific timeline or even promise a successful result. 😉 

Regarding the issue at hand, it's essential for primitive types to be accepted as payloads and be adorned with Swagger's @Schema annotations, meaning accepting Schema<?> objects as payload types. In my current codebase, I've crafted a workaround for this. Integrating this capability directly into Springwolf would be a valuable enhancement. I'll go ahead and draft a ticket for this.

I'll get back to you once I have some bandwidth to start working on implementing this.

Best regards!

**Comment by stavshamir** [comment]
Thanks for the heads up, but don't worry, Springwolf is an open-source project and every attempt contribution is appreciated :)
You can look at our [short contribution guide](https://github.com/springwolf/springwolf-core/blob/master/CONTRIBUTING.md#i-want-to-contribute) and join the [discord server ](https://discord.gg/4eNYDc8Z) if you prefer more synchronic communication.

Good luck!

**Comment by jenarp** [comment]
After further examination, I realized I made an error in my initial assessment. A simple string, when categorized as 'string' in the spec, is indeed displayed correctly in the UI. As such, I'd like to request to close this ticket.

However, I did notice a smaller issue: it seems that several Swagger documentation annotations, such as 'minimum' and 'maximum', aren't fully reflected in the UI. While they are present in the specification, they don't seem to appear in the user interface. Additionally, in my opinion it would be great if the UI explicitly displayed the type, like 'string', somewhere if the payload is of such primitive type (see the image of the UI attached to the initial ticket). 
For reference, I noticed that the [AsyncAPI React library](https://github.com/asyncapi/asyncapi-react) does showcase these annotations. While this is a minor point and the current UI already offers a lot of value, I believe such additions could enhance the user experience further. If you think it's relevant, I'm willing to create a separate ticket for this matter. Otherwise, we can consider it a minor point for potential future improvements.

**Comment by timonback** [comment]
To simplify understanding the issue in the future, I suggest to close this one and open a new enhancement issue with the description you provided in the last comment.

Again, feel free to contribute it and dive into the Angular springwolf-ui, which can be tested locally.
I agree, it would be great to reach feature parity with the react version.

Hacktoberfest is happening in a couple days again, which is a great opportunity to contribute to Open Source.

FYI: If you want to test springwolf with their ui, you can use https://github.com/timonback/springwolf-asyncapi-ui However that is a demo project  at this point.

**Comment by jenarp** [comment]
Closed: The initial assumption underlying this ticket was found to be incorrect.
