### ISSUE TITLE
Enhancement: Add More Spec Details to the UI

### ISSUE THREAD

**Issue by jenarp** [springwolf/springwolf-core#378]
**Description:**
I've noticed that certain Swagger documentation annotations, notably 'minimum' and 'maximum', are present in the specification but are not reflected in the UI. Additionally, payloads with primitive types like 'string' don't have their type explicitly displayed in the UI.

**Steps to Reproduce:**

1. Add annotations like 'minimum' or 'maximum' to your Schema Annotation or use a primitive type as payload.
2. Verify they appear in the specification and note that 'type: string' (or similar) is present.
3. Observe the absence of these details in the UI.

**Expected Behavior:**
Swagger annotations, such as 'minimum' and 'maximum', would be a valuable addition to the UI. It would also be beneficial for the UI to display primitive types explicitly.

**Actual Behavior:**
Annotations are missing, and primitive types are not distinctly represented.

**Suggested Fix:**

Enhance the UI to incorporate Swagger annotations more comprehensively.
Display primitive payload types clearly.
Aim for parity with the display capabilities of the [AsyncAPI React component](https://github.com/asyncapi/asyncapi-react).

**Status:**

- [ ] Const
- [x] Enum
- [x] Items
- [x] MaxItems
- [x] MinItems
- [x] Required
- [x] name: String (default: "")
- [x] title: String (default: "")
- [x] multipleOf: double (default: 0.0)
- [x] maximum: String (default: "")
- [x] exclusiveMaximum: boolean (default: false)
- [x] minimum: String (default: "")
- [x] exclusiveMinimum: boolean (default: false)
- [x] maxLength: int (default: Integer.MAX_VALUE)
- [x] minLength: int (default: 0)
- [x] pattern: String (default: "")
- [ ] maxProperties: int (default: 0)
- [ ] minProperties: int (default: 0)
- [ ] requiredProperties: String[] (default: {})
- [ ] requiredMode: Schema.RequiredMode (default: Schema.RequiredMode.AUTO)
- [x] description: String (default: "")
- [x] format: String (default: "")
- [x] ref: String (default: "")
- [x] nullable: boolean (default: false)
- [x] example: String (default: "")
- [ ] externalDocs: ExternalDocumentation (default: @ExternalDocumentation)
- [ ] deprecated: boolean (default: false)
- [x] type: String (default: "")
- [ ] allowableValues: String[] (default: {})
- [ ] defaultValue: String (default: "")
- [ ] discriminatorProperty: String (default: "")
- [ ] hidden: boolean (default: false)
- [ ] enumAsRef: boolean (default: false)
- [x] types: String[] (default: {})
- [x] exclusiveMaximumValue: int (default: 0)
- [x] exclusiveMinimumValue: int (default: 0)

**Comment by aerfus** [comment]
Hello,
@jenarp , @timonback let me try accomplish this one.

AsyncAPI Studio -> https://studio.asyncapi.com/
shows minimum and maximum values as follows:
![minimum_maximum_example](https://github.com/springwolf/springwolf-core/assets/8309418/2699810c-7133-45d6-8f4d-3acdd1aa95f3)

Need to display in a similar way, right?

**Comment by timonback** [comment]
Hi @aerfus ,
sure, thank you for volunteering.
Feel free to take inspiration from asyncapi studio and get creative :)

In case you plan larger changes, it might be easier for us, when you start from the branch feat/asyncapi-3 as it contains some ui refactorings.

**Comment by aerfus** [comment]
Hi @timonback,

I've added `types` to payloads headers.
Working on maximum and minimum values

![new_schemas_presentation](https://github.com/springwolf/springwolf-core/assets/8309418/3b03ccd2-3da7-46ca-9cfb-73f877587344)

**Comment by aerfus** [comment]
### Dev test
Screenshot 1
![image](https://github.com/springwolf/springwolf-core/assets/8309418/2a36353f-f186-43d1-857b-99ceefb101e6)
Screenshot 2
![image](https://github.com/springwolf/springwolf-core/assets/8309418/d247d12a-4998-4b96-b1f8-01ca3fa993c8)

**Comment by timonback** [comment]
@jenarp @aerfus As the first PR is merged, lets move the conversation to the issue.

Thank you @aerfus for adding maximum and minimum fields to springwolf-ui.

---

@jenarp Can you add a list of fields that you are interested in?

Based on the json-schema `JsonSchemaGeneration` I can imagine the following fields:
 - [ ] Const
 - [x] Description
 - [x] Enum
 - [x] Nullable
 - [ ] Format
 - [x] Items
 - [x] Maximum
 - [x] Minimum
 - [ ] MaxItems
 - [ ] MinItems
 - [ ] MaxLength
 - [ ] MinLength
 - [ ] MultipleOf
 - [x] Name
 - [ ] Pattern
 - [x] Required
 - [x] Title
 - [x] Type

**Comment by jenarp** [comment]
Yes, examining the JSON schema is beneficial!
I think, Swagger uses this as well.
When you look into the Swagger Schema within the library `io/swagger/core/v3/swagger-annotations-jakarta/2.2.16/swagger-annotations-jakarta-2.2.16`, particularly at `package io.swagger.v3.oas.annotations.media`, you'll find a comprehensive list of annotations used to define the schema. Here’s a list of interesting fields (not exhaustive) from the Schema annotation, including those from your list that weren't duplicates:

- [ ] Const
- [x] Enum
- [x] Items
- [ ] MaxItems
- [ ] MinItems
- [x] Required
- [x] name: String (default: "")
- [x] title: String (default: "")
- [ ] multipleOf: double (default: 0.0)
- [x] maximum: String (default: "")
- [ ] exclusiveMaximum: boolean (default: false)
- [x] minimum: String (default: "")
- [ ] exclusiveMinimum: boolean (default: false)
- [ ] maxLength: int (default: Integer.MAX_VALUE)
- [ ] minLength: int (default: 0)
- [ ] pattern: String (default: "")
- [ ] maxProperties: int (default: 0)
- [ ] minProperties: int (default: 0)
- [ ] requiredProperties: String[] (default: {})
- [ ] requiredMode: Schema.RequiredMode (default: Schema.RequiredMode.AUTO)
- [x] description: String (default: "")
- [ ] format: String (default: "")
- [ ] ref: String (default: "")
- [x] nullable: boolean (default: false)
- [ ] example: String (default: "")
- [ ] externalDocs: ExternalDocumentation (default: @ExternalDocumentation)
- [ ] deprecated: boolean (default: false)
- [x] type: String (default: "")
- [ ] allowableValues: String[] (default: {})
- [ ] defaultValue: String (default: "")
- [ ] discriminatorProperty: String (default: "")
- [ ] hidden: boolean (default: false)
- [ ] enumAsRef: boolean (default: false)
- [ ] types: String[] (default: {})
- [ ] exclusiveMaximumValue: int (default: 0)
- [ ] exclusiveMinimumValue: int (default: 0)

This list includes both the original fields you provided and the additional ones that were not duplicates. 
It’s important to note that this list may not be exhaustive!

**Comment by aerfus** [comment]
Hi @timonback , @jenarp,
currently I'm working on exclusiveMinimum and exclusiveMaximum.

The thing I've noticed is in https://studio.asyncapi.com/
the values are Numeric, not Boolean.
The same is stated here https://unpkg.com/browse/@asyncapi/avro-schema-parser@1.0.0/README.md.

I'll enhance the current implementation with Booleans.
FYI

**Comment by aerfus** [comment]
Hi @timonback ,
I've started working on tests for schema.component.ts.
Checkout was from timonback:test/add-jest-testing-to-springwolf-ui

**Comment by timonback** [comment]
> Hi @timonback , I've started working on tests for schema.component.ts. Checkout was from timonback:test/add-jest-testing-to-springwolf-ui

Hi @aerfus,
I am about to merge the jest PR. Due to squashing, you will need to rebase from the `master` branch. Sorry for the inconvenience.

**Comment by timonback** [comment]
Closed accidentally.

We updated the mapping in the backend, currently supported fields can be found in https://github.com/springwolf/springwolf-core/blob/master/springwolf-core%2Fsrc%2Fmain%2Fjava%2Fio%2Fgithub%2Fstavshamir%2Fspringwolf%2Fschemas%2FSwaggerSchemaUtil.java which require Angular frontend changes only to be displayed - besides updating the kafka example (add the field to the @Schema annotation as done for i.e. maximum) to demonstrate it

Any help is welcome

**Comment by aerfus** [comment]
Hi @timonback ,
sorry my bad putting Resolves #378 in PRs.
Could you reopen this issue?

**Comment by timonback** [comment]
In the new ui, a lot more fields are being displayed, namely the ones listed here: https://github.com/springwolf/springwolf-core/blob/master/springwolf-ui/src/app/models/schema.model.ts

Due to low activity, I will close this issue with the upcoming release.
Anyone feel free to suggest/contribute individual fields that are missing.
