### ISSUE TITLE
Allow info-extensions in application.yml/props

### ISSUE THREAD

**Issue by tvahrst** [springwolf/springwolf-core#395]
Springwolf supports the definition of  'static' basic informations of an asyncapi spec (info, id, servers) by
* providing an Docket Bean  or
* providing the necessary informations as environment properties (for example in application.yml) with the prefix `springwolf.docket.*`. 

The second approach (docket data via environment)  does currently not support the definition of extensions for the info-block. So it isn't possible to provide docket data so that the resulting asyncapi looks like this (info include `x-additional-field`):

```
{
  "asyncapi": "2.6.0",
  "info": {
    "title": "my-kafka-worker",
    "version": "1.0.0",
    "x-additional-field": "trulallal"
  },
  ...
}
```

For `contact` and `license`  in turn there is a possibility to define extensions in the environmet, like this:

```
springwolf.docket.info.contact.extension-fields.x-userid = t.vahrst
```

I suggest to support the same extension pattern which allows extensions for 'contact' and 'license' to be appliable for 'info'.

**Comment by timonback** [comment]
Thank you for the report, the issue has been addressed in the new release.

An update on the documentation is welcome: https://github.com/springwolf/springwolf.github.io/issues/58

Feel free to reopen this issue if there is still something missing.
