### ISSUE TITLE
DefaultAsyncApiDocketService: cache docket instance if constructed from environment properties

### ISSUE THREAD

**Issue by tvahrst** [springwolf/springwolf-core#409]
The `DefaultAsyncApiDocketService` has a service method `getAsyncApiDocket()` which provides the current Docket instance. If the application defines a Docket **bean**, `DefaultAsyncApiDocketService` holds a reference on this bean and delivers the bean on every `getAsyncApiDocket()` invocation. 

If there is no Docket bean, `DefaultAsyncApiDocketService` creates an `AsyncApiDocket` object with properties from environment. This happens again with every invocation of `getAsyncApiDocket()`. As there are many 'uses' of this service and the spring environment is stable, this creates unnecessary overhead.

The environment-based docket instance should be cached once created.

**Comment by timonback** [comment]
Thank you for the report, the issue has been addressed in the new release.

Feel free to reopen this issue if there is still something missing.
