### ISSUE TITLE
Align Spring cloudstream example with other examples

### ISSUE THREAD

**Issue by timonback** [springwolf/springwolf-core#420]
**Describe the feature request**
When the cloud-stream example and plugin was build, it was built in a simple way.

To streamline and simplify our testing efforts, we like to align the cloud stream example with the other examples. Also, the bug https://github.com/springwolf/springwolf-core/issues/415 was found, which indicates that there could be (more) bugs (which do not have to be addressed as part of this issue).

Steps:
1. [ ] change Consumer consumer-method-input-topic to another-topic with payload AnotherPayloadDto
2. [ ] change Consumer input-topic to example-topic with payload ExamplePayloadDto
3. [ ] change producer output-topic to another-topic with payload AnotherPayloadDto

Expected topics & payloads (using sqs as a blueprint): https://sqs.demo.springwolf.dev/springwolf-ui/asyncapi-ui.html
Code: https://github.com/springwolf/springwolf-core/tree/master/springwolf-examples/springwolf-cloud-stream-example

Feel free to contribute and/or assist in just a single step instead of the full journey. We expect changes in the cloud-stream example only, unless we might hit bugs.

**Comment by JayOaks** [comment]
Hi,
I would like to help but I am confused.
Can I ask for more information?

**Comment by timonback** [comment]
Hi @JayOaks 
Sure, go ahead. Or join us on Discord :)
