### ISSUE TITLE
Kafka publishing producer creation fails in Spring Boot 3.2

### ISSUE THREAD

**Issue by salmar** [springwolf/springwolf-core#443]
**Describe the bug**

The signature of one of the methods used when creating the publishing producer has changed in Spring Boot 3.2. This makes the creating of the producer fail at startup. The `buildProperties` method is now accepting a an SSL bundle as shown [here](https://github.com/spring-projects/spring-boot/blob/ec6415f04bf3e3ec47ab9600c744e5199ca85be0/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/kafka/KafkaProperties.java#L496).

**Dependencies and versions used**
Spring Boot 3.2.0-RC2
`springwolf-kafka`  `0.16.0`.

**Code example**

Enabled the creation of the producer with the following properties:

```
springwolf.plugin.kafka.publishing.enabled=true
springwolf.plugin.kafka.publishing.producer.bootstrap-servers=localhost:9092
springwolf.plugin.kafka.publishing.producer.key-serializer=org.apache.kafka.common.serialization.IntegerSerializer
springwolf.plugin.kafka.publishing.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
```

**Stack trace and error logs**

This is the exception thrown at startup:

```
An attempt was made to call a method that does not exist. The attempt was made from the following location:

    io.github.stavshamir.springwolf.producer.SpringwolfKafkaTemplateFactory.buildKafkaTemplate(SpringwolfKafkaTemplateFactory.java:28)

The following method did not exist:

    'java.util.Map org.springframework.boot.autoconfigure.kafka.KafkaProperties$Producer.buildProperties()'
```

**Comment by sam0r040** [comment]
Hi @salmar
thanks a lot for the heads up. It looks like there will be a breaking change in Spring Boot autoconfigure. We do not support release candidates of newer spring boot versions and will update to Spring Boot 3.2.x as soon as it is released.

If you need to use a release candidate of Spring Boot 3.2.x, you can supply your own SpringwolfKafkaTemplateFactory Bean that you can adapt to this change.

**Comment by timonback** [comment]
Version 0.17.0 does support spring boot 3.2
