### ISSUE TITLE
Extend method annotations with target ANNOTATION_TYPE

### ISSUE THREAD

**Issue by ibrok** [springwolf/springwolf-core#448]
**Describe the feature request**
Add ElementType.ANNOTATION_TYPE to all annotations that currently only have ElementType.METHOD as Target.

**Motivation**
We like to write and use custom constructed annotations to standardise and simplify the use of annotations in our applications. This is currently not possible for annotations like AsyncPublisher or SnsAsyncOperationBinding, as they only have Target ElementType.METHOD. 
By creating our own custom annotation, we would have to define our custom headers only once for example. 
Or could standardise the use with other annotations like micrometers @ Timed.

**Technical details**
Add ElementType.ANNOTATION_TYPE to all annotations that currently only have ElementType.METHOD

**Describe alternatives you've considered**
I dont think there is an alternative. Either it is allowed or it isn't.

**Comment by sam0r040** [comment]
Hi @ibrok, this is a good enhancement to Springwolf.

We see the following steps:

- [ ] Add ElementType.ANNOTATION to all Springwolf annotations
- [ ] Add a Test that methods with a custom meta annotation are also evaluated by Springwolf

If you or anybody else who wants to contribute, feel free to start.

**Comment by timonback** [comment]
Thank you for the report, the issue has been addressed in the new release.

Feel free to reopen this issue if there is still something missing.
