### ISSUE TITLE
Question on generated payload for List of objects (AsyncAPI spec)

### ISSUE THREAD

**Issue by aerfus** [springwolf/springwolf-core#449]
Hello,

In the example below Kafka configured to consume a List of objects

https://github.com/springwolf/springwolf-core/blob/34c1a26b1315dc5e043a43d934003d5cc2cf96d7/springwolf-examples/springwolf-kafka-example/src/main/java/io/github/stavshamir/springwolf/example/kafka/consumers/ExampleConsumer.java#L33

At the same time, using generated AsyncAPI spec we can publish only 1 model per request, i.e.
```json
{
    "title": "AnotherPayloadDto",
    "payload": {
        "$ref": "#/components/schemas/io.github.stavshamir.springwolf.example.kafka.dtos.AnotherPayloadDto"
    }
}
```

So shouldn't it be like this instead?
```json
{
    "title": "AnotherPayloadDto",
    "payload": {
        "type": "array",
        "items": {
            "$ref": "#/components/schemas/io.github.stavshamir.springwolf.example.kafka.dtos.AnotherPayloadDto"
        }
    }
}
```

**Comment by timonback** [comment]
Hi @aerfus 
The example uses a Spring batched listener, meaning that the payload is AnotherPayloadDto. The consumers processes a List of messages and acknowledge the full list at the end.

True, we make the assumption that users do not consume a payload of type list, but instead assume that a batch listener is used.

This might be related to https://github.com/springwolf/springwolf-core/issues/433

**Comment by timonback** [comment]
If you want the list, you can define your own type (verified in #451) or wait for the above mentioned PR.
```
@Data
    @NoArgsConstructor
    private static class ListWrapper extends ArrayList<String> {}
```

**Comment by aerfus** [comment]
Hi @timonback ,
thank you so much for the explanation!
Now it's clear to me.
