### ISSUE TITLE
No Producer configuration available in AsyncApiConfiguration.java

### ISSUE THREAD

**Issue by SaiAravindVemuri** [springwolf/springwolf-core#46]
when tried adding producer data for AsyncApiConfiguration.java for AMQP example I'm getting issue for binding
![image](https://user-images.githubusercontent.com/50715301/157216456-103543da-8c02-4f6b-a6ac-5ac2f54b1ca6.png)

kindly help with the configuration for producer in AMQP(RMQ)

**Comment by stavshamir** [comment]
You should use:
```java
import com.asyncapi.v2.binding.amqp.AMQPOperationBinding;

...
 .binding(ImmutableMap.of("amqp", new AMQPOperationBinding()))
...
```

**Comment by SaiAravindVemuri** [comment]
Thank you this worked for me.
