### ISSUE TITLE
Security to the generated specs on UI

### ISSUE THREAD

**Issue by SaiAravindVemuri** [springwolf/springwolf-core#47]
How can we add security to the specs that we've generated while viewing the UI something we have for swagger ui screen

Much thanks in advance..

**Comment by stavshamir** [comment]
Could you elaborate please? Do the security details you need are part of the async api spec?

**Comment by stavshamir** [comment]
Oh, you mean you would like to have security on the API and UI themselves?
I did not have a plan to support this, but if you would like to try and provide a PR that would be great.

**Comment by linghengqian** [comment]
> Oh, you mean you would like to have security on the API and UI themselves?
> I did not have a plan to support this, but if you would like to try and provide a PR that would be great.


UI security should not be dealt with here. But if possible, can the document give the path of the resource that needs to be secured? This will help with spring Security integration. It looks like
```java
 
     @Bean 
     @Order(0)     public SecurityFilterChain resources(HttpSecurity http) throws Exception { 
         http.requestMatchers((requestMatchers) -> requestMatchers 
                         .antMatchers("/swagger-ui/**") 
                         .antMatchers( "/v3/api-docs/**") 
                         .antMatchers( "/webjars/**")) 
                 .authorizeRequests((requests) -> requests.anyRequest().hasAnyRole("ENDPOINT_ADMIN"))
                 .httpBasic(Customizer.withDefaults());
         return http.build(); 
     }

     @Bean 
     public UserDetailsService userDetailsService() { 
         User.UserBuilder users = User.builder();          BCryptPasswordEncoder encoder = new BCryptPasswordEncoder(14);          InMemoryUserDetailsManager manager = new InMemoryUserDetailsManager();         manager.createUser(users.username("admin").password("{bcrypt}" + encoder.encode("123456")).roles("ENDPOINT_ADMIN").build()); 
         return cachingUserService; 
     }
```

**Comment by stavshamir** [comment]
That's great input @linghengqian, thanks a lot. I will add the paths to the documentation site, see [issue](https://github.com/springwolf/springwolf.github.io/issues/3).
