### ISSUE TITLE
Adding example values to payload

### ISSUE THREAD

**Issue by SaiAravindVemuri** [springwolf/springwolf-core#48]
how can we add example values for the payload to publish via asyncAPI ui?

**Comment by stavshamir** [comment]
At the moment examples can't be added to the async api document, but you can edit the generated payload example in the Example tab and publish it.

**Comment by 19941112** [comment]
> By the way, I'm starting a [discord server for springwolf](https://discord.gg/PU9MGcBJ) Please join, we can also talk there if you fell more real time communication may help!

the link you've shared isn't working to join. Kindly help me with the new link.
