### ISSUE TITLE
Update to AsyncApi spec 3.0

### ISSUE THREAD

**Issue by timonback** [springwolf/springwolf-core#494]
**Describe the feature request**
Update to AsyncApi spec 3.0

**Motivation**
The spec got released and we want to update to the latest version

**Status**
- [x] Update backend AsyncApi pojos
- [x] Update springwolf-ui

**Technical details**
- https://www.asyncapi.com/blog/async-api-spec-3.0-release
- https://www.asyncapi.com/docs/migration/migrating-to-v3

**Describe alternatives you've considered**
None

**Comment by timonback** [comment]
Thank you @ctasada for starting on this

**Comment by ctasada** [comment]
Work started with https://github.com/springwolf/springwolf-core/pull/501

**Comment by Pakisan** [comment]
@ctasada hi!

Sorry, was off for a while. Mb we can re co-op on our bindings? v3 is ready to use

**Comment by ctasada** [comment]
Hi @Pakisan,

We decided to move forward with our own implementation and we are almost done with the migration to AsyncAPI v3.
 
 As you can see at https://github.com/springwolf/springwolf-core/tree/master/springwolf-asyncapi we created a new module from scratch, using the AsyncAPI v3 published examples to validate the output correctness, and finding in the way multiple typos in the examples, mainly with the bindings.
 
The work to migrate `springwolf-core` is happening in https://github.com/springwolf/springwolf-core/pull/507 which we plan to merge to master over the next days.

For sure we would love to get your contributions and feedback on the existing work.

**Comment by timonback** [comment]
Re-opened for visibility and to indicate that AsyncApi v3 is part of the next release

**Comment by timonback** [comment]
The new version is out now. Closing this issue.

**Comment by Pakisan** [comment]
@ctasada @timonback hi!

It’s awesom that you have finished your own implementation🎉

You can reuse examples from my repo to check implementation correctness 

Also check out this issue - https://github.com/asyncapi/jasyncapi/issues/185
