### ISSUE TITLE
Add `@KafkaHandler` example to `springwolf-examples/springwolf-kafka-example`

### ISSUE THREAD

**Issue by stavshamir** [springwolf/springwolf-core#50]
Now that support for `@KafkaHandler` has been added in `0.4.0`, it would be nice to add such an example to the [kafka plugin example project](https://github.com/springwolf/springwolf-core/tree/master/springwolf-examples/springwolf-kafka-example).
This would require to:

- [ ] Add a class with two `@KafkaHandler` methods, with a non-primitive payload (can use the existing example DTOs).
- [ ] Since this project also serves as integration test, update the [expected async api doc](https://github.com/springwolf/springwolf-core/blob/27b4703e2505e00b219778a4e890704ea74ca01c/springwolf-examples/springwolf-kafka-example/src/test/resources/asyncapi.json) with the new channel.
- [ ] Verify that publishing from the UI works.

**Comment by Crain-32** [comment]
Is this resolved with the new Class Listener? https://github.com/springwolf/springwolf-core/blob/master/springwolf-examples/springwolf-kafka-example/src/main/java/io/github/stavshamir/springwolf/example/consumers/ExampleClassLevelKafkaListener.java

**Comment by stavshamir** [comment]
Yes, thanks.
