### ISSUE TITLE
Support Kafka Header

### ISSUE THREAD

**Issue by sshemirani** [springwolf/springwolf-core#51]
There should be a support to add Kafka headers. For example the spring __TypeId__ header should be provided in order for the spring to serialise and deserialize payloads. Without this header the publish button on the example tab cannot work as it need a __TypeId__ header to do its job. 

Thanks and keep up the good work.

**Comment by stavshamir** [comment]
Thanks for the kind words!
I agree that this is a needed improvement. I'll try to add it in the next version.

**Comment by sam0r040** [comment]
I decided to give it a try and started with the changes needed in the backend in PR https://github.com/springwolf/springwolf-core/pull/86

Let me know what you think... 

If we are happy with the backend implementation I would also try to provided the change for the frontend.

**Comment by stavshamir** [comment]
Thanks for the great work of @sam0r040 and @timonback , this will be included in the next release 🥳
