### ISSUE TITLE
not validating the queue

### ISSUE THREAD

**Issue by 19941112** [springwolf/springwolf-core#52]
when added producer configuration and trying to publish message from the ui it isn't validating the queue please help me to understand a way in validating the queue

![image](https://user-images.githubusercontent.com/50715301/159892138-862891ed-93d6-48ff-8fb0-1eaae17cb35d.png)

**Comment by stavshamir** [comment]
I'm sorry but I am not sure what you mean by validating the queue - do you mean that you would like springwolf to validate the existence of a queue?

**Comment by SaiAravindVemuri** [comment]
so can you clarify what should we give in the channel("<<here?>>") i'm giving queue name to which publisher is publishing
in that place if in case we don't have queue name can we take it with binding ?

**Comment by stavshamir** [comment]
I'm still nut sure I understand your question. I will close this for now.
