### ISSUE TITLE
Plans for future

### ISSUE THREAD

**Issue by gomonp** [springwolf/springwolf-core#54]
Hi everyone who develops this tool!
I've tried to use this tool on my production project to make useful API for Rabbit AMQP that we expose internally.
But found that in fact library covers at most 10% of [AsyncAPI specification ](https://www.asyncapi.com/docs/specifications/v2.0.0)
Also I found that for some reason it was designed in a way that restricts any extension of existing "Services/Providers/Models", and all used models are not from _async-api_ dependency but own-created and they doesn't hold enough properties to match AsyncAPI Spec.
Also it is not possible to extend Generated Spec with some custom descriptions of operations/parameters (e.g. via annotations).

So, looking at this facts I have single question - is it planned to support this project and make it usable not only for "Hello World" application?

Kind regards,
Pavlo

**Comment by stavshamir** [comment]
Hi @gomonp, thanks for the interest in the project!

1. I'm not sure what you mean by not covering most of the AsyncAPI specification - the models were indeed own-created in the past, but in the last few versions I am using the [official models](https://github.com/asyncapi/jasyncapi).
2. When you write restriction of extension, do you mean that you would like to be able to specify more channels and models manually, apart from those generated automatically?
3. About custom descriptions, there is a related opened issue #35, and I agree that this is an important enhancement which I do intend to implement in the coming versions.

I would argue that this project is usable, although for basic use-cases. I would like to further improve it and have many ideas for such improvements, but as I am working on this project on my free time and mostly alone, it will probably take some time.

If you would like to contribute this could of course speed things up :) Please let me know if you have more ideas or questions!

**Comment by stavshamir** [comment]
Closed due to inactivity.
