### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by nschwalbe** [springwolf/springwolf-core#542]
**Describe the feature request**
Markdown support in description fields

**Motivation**
A more structured and formatted documentation. Currently every text is just a line without breaks or paragraphs. This is very difficult to read for some longer descriptions.

**Technical details**
Maybe include angular ngx-markdown library

**Describe alternatives you've considered**
-

**Comment by timonback** [comment]
Hi @nschwalbe,
Thank you for the suggestion.

Using Commonmark (markdown) for the structured text is great, as it is suggested the AsyncApi spec. See https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#fixed-fields-1

The description field of the info object is a great start.
Do you use a long description for the Channels & Schemas as well?

Feel free to get started on it (or anyone how wants to contribute it)

**Comment by nschwalbe** [comment]
Yes, exactly. We want to describe the info, channel and schema in more detail.
My colleague is preparing a PR for the ngx-markdown library which uses marked which is nearly complete commonmark 3.0 compliant: https://github.com/markedjs/marked/discussions/1202#discussioncomment-4192078

**Comment by timonback** [comment]
Thank you for the contribution, it is part of the latest release.

Feel free to reopen this issue if there is still something missing.
