### ISSUE TITLE
gradle plugin for build-time generation

### ISSUE THREAD

**Issue by typekpb** [springwolf/springwolf-core#55]
I like the idea of generating documentation in the build time.
Adding idea of an option to generate asyncapi json|yaml in the build time using gradle.
Generating the html UI I see only as an optional step, as there are usually already provided solutions that can visualise the provided spec in a fancy way.

**Comment by stavshamir** [comment]
That's a good idea, but it would require some more heavy design and programming than I have time now. I've never written a maven plugin. If anyone would like to contribute, I'd be happy to help and support.

**Comment by stavshamir** [comment]
See #134
