### ISSUE TITLE
When using the same protobuf message for kafka and Rest WS, in swagger api docs Protobuf schema types contain full package name

### ISSUE THREAD

**Issue by serdaryesilmurat** [springwolf/springwolf-core#566]
In our spring project, we are using same protobuf messages for both our Kafka topics and Rest WS end points.

```protobuf
message CustomProtoMessageData {
  int32 data = 1;
}

message CustomProtoMessage {
  repeated CustomProtoMessageData content = 1;
}
```

In that case, in the generated `swagger api docs`, these protobuf messages used for both Kafka and Rest WS are shown with full package name in Schema definition such as:

> com.company.sample.message.CustomProtoMessage

When we disable spring wolf by setting `springwolf.enabled=false`, schema is generated with name "CustomProtoMessage" which is what we want to see.

**Dependencies and versions used**
`springwolf-kafka` version: `0.17.0`.
`SpringDoc OpenAPI Starter Common` version: `2.3.0`

**Code example**
```java

// Kafka listener
    @KafkaListener(topics = "custom-topic")
    public void consume(CustomProtoMessage msg) {
    }

// Rest WS ecdpoint
    @PostMapping("/custom")
    public void writeData(@RequestBody CustomProtoMessage msg) {
    }
```

**Workaround**
To solve the problem, as a workaround we separated the message for Kafka listener. As you can see, typeof "content" in CustomProtoMessageForKafka is any, because in the bug case, schema definition for CustomProtoMessageData contain full package name too. We call "unpack" method of "Any" instance in kafka listener method to resolve to CustomProtoMessageData type.

```protobuf
message CustomProtoMessageData {
  int32 data = 1;
}

message CustomProtoMessage {
  repeated CustomProtoMessageData content = 1;
}

message CustomProtoMessageForKafka {
  repeated google.protobuf.Any content = 1;
}
```

```java

// Kafka listener
    @KafkaListener(topics = "custom-topic")
    public void consume(CustomProtoMessageForKafka msg) {
    }

// Rest WS ecdpoint
    @PostMapping("/custom")
    public void writeData(@RequestBody CustomProtoMessage msg) {
    }
```

**Comment by timonback** [comment]
Hi @serdaryesilmurat,
have you seen the `springwolf.use-fqn` setting? Using that, you can specify whether Springwolf should use fully-qualified class names (including the package name).

Under the hood, the same mechanism is used by swagger.

Does that answer your question?

**Comment by serdaryesilmurat** [comment]
Hi. Thanks for quick reply, but that is the opposite of what i want 😅 
springwolf.use-fqn (or springdoc.use-fqn) causes the schema names with package names. I want schema names to be generated from the simple java class names.

By the way, as I side note, I use "swagger-typescript-api" for generating typescript client API using the swagger docs generated. When schema types contain package name, generated frontend api contains types with full package name which unnecessarily clutters the generated client api code. That is the main reason for opening this issue.

**Comment by timonback** [comment]
I am not sure, if I am understanding you correctly.
You always want to use the simple class name (springwolf + swagger).

When you use `springwolf.use-fqn=false` then Springwolf will always use the simple class name.
However, it might be that other library use the same mechanism from swagger do not unset the `use-fqn` setting correctly.

Still, we expect when every library (Springwolf + springdoc) is configured with `use-fqn=false` there shouldn't be an issue.

**Comment by serdaryesilmurat** [comment]
You are absolutely right. In another lib we used, `springwolf.use-fqn` property was set to `true`. When i set it to false in our project, it worked as you said. Thanks for the support 😉
