### ISSUE TITLE
support for SQS

### ISSUE THREAD

**Issue by typekpb** [springwolf/springwolf-core#57]
as Asyncapi supports SQS: https://www.asyncapi.com/docs/specifications/v2.3.0, it would be nice, if the tool could handle it as well.

**Comment by stavshamir** [comment]
I've been asked for this before, so this will probably be implemented in the future. If you wish to contribute, it would be more than welcome!

**Comment by rogerioesteves** [comment]
@stavshamir I also have interest in this feature. Do you have some documentation to implement this feature. Do you have some advice or pattern to be drive. I was looking for some pattern and I think that using spring cloud aws could be a good idea. What do you think?

**Comment by stavshamir** [comment]
It is a bit different than the AMQP and Kafka annotations, but looks pretty straight forward to implement. 
The first thing to do will be to create an example project that can be used to test the plugin. 

If you could create one, showcasing the use of SQS and SNS and runnable via docker-compose, it could advance the creation of this plugin.

Please take a look at the springwolf-example projects, fork springwolf-core, and try to create something similar for SNS and SQS. It should be using springwolf yet, but it's important that it is runnable.

**Comment by rogerioesteves** [comment]
@stavshamir thanks! I will study ways to implement SQS first all. I will following your suggestions and I will go back with news

**Comment by stavshamir** [comment]
Great, let me know if I can do anything to help. I will create a branch with the project skeleton so you will have something to start working with.

**Comment by stavshamir** [comment]
@rogerioesteves I added a template project, see [branch](https://github.com/springwolf/springwolf-core/tree/feature/sqs-plugin)

**Comment by stavshamir** [comment]
Closing due to lack of public interest.
