### ISSUE TITLE
Feature to hide buttons inside kafka publish operations

### ISSUE THREAD

**Issue by achabdo** [springwolf/springwolf-core#609]
**Possibilité to hide buttons inside kafka publish or subscribe operation**
We want an option to hide unnecessary buttons that can be shown to users using our Kafka documentation.

**Motivation**
The problem is that users can send Kafka notifications to our Kafka topics, which can be dangerous. When you send a Kafka message to our broker servers, this data is used as replication, and it 's inserted into the database. We don't want users to have the ability to do that, and we want to hide completely the publish button, as shown in the following image.
![Capture](https://github.com/springwolf/springwolf-core/assets/11176293/20c060d8-6e1c-4035-87b2-d61a03790fc1)

**Technical details**
We want to have the ability to configure that by using  AsyncApiDocket asyncApiDocket() even if it 's a deprecated methode as we still using it in our project. Or by using the application.yml in the future.
For exemple :
var docket =  AsyncApiDocket.builder().hidePublishButton(true)

**Comment by timonback** [comment]
Hi @achabdo , true, the ui shows all functionality regardless of how Springwolf is configured.

To enable publishing, you have to explicitly activate the publishing setting in Springwolf (i.e. `springwolf.plugin.kafka.publishing.enabled=true`).

Just to clarify, you want to hide the publish button in the ui, when the publishing functionality is disabled in Springwolf?

**Comment by achabdo** [comment]
Yes , I want to hide the publish button when the publishing is disabled as users may think that they have the ability to send kafka notifications which can lead to confusion.

**Comment by timonback** [comment]
Got it.

For this, Springwolf-ui would need to get the information from the backend. The backend would need to offer the information through some kind of new endpoint — combining the information from each activated plugin.

I see also another solution, which is easy to implement and might be good enough. The button stays visible and when pressed, a better error message is shown (i.e.: publishing failed. This feature might have been disabled by the administrator of this application). Based on the http response status code, the authorization error can differentiated.

Is the second option good enough for you?
Feel free to get started on it.

**Comment by achabdo** [comment]
I will go with the first option. Thank you.
