### ISSUE TITLE
Add support for STOMP in SpringWolf

### ISSUE THREAD

**Issue by linghengqian** [springwolf/springwolf-core#61]
- For users of the `Spring` ecosystem, the dependency of `org.springframework.boot:spring-boot-starter-websocket` is usually used to provide `STOMP` and `sock.js` protocol encapsulation for `Websocket`. `STOMP` is a sub-protocol of `websocket`, and the behavior and paradigm of `STOMP` are defined at https://www.asyncapi.com/docs/specifications/v2.4.0 . I hope there will be a corresponding treatment in `SpringWolf`.
- A simple demo is at https://github.com/spring-tips/controllers/tree/main/websockets , which helps to locate the actual model binding scenario.

**Comment by Crain-32** [comment]
After a free Afternoon and I want a way to document my own project's `STOMP` Server, here are my notes on trying to get this to work.

I don't believe this feature is possible right now, as Springwolf uses the [1.0.0](https://github.com/springwolf/springwolf-core/blob/27b4703e2505e00b219778a4e890704ea74ca01c/springwolf-core/build.gradle#L21) `bindings` for its internals. This results in the `buildOperationBinding` method for the `AbstractChannelScanner` being unusable, as there is no `STOMPOperationBinding` declared in AsyncAPI's Repository. 

There is also talk about deprecating the `bindings` Repository set to [happen soon](https://github.com/asyncapi/bindings/issues/113#issuecomment-1116017002) meaning that this issue likely can't be resolved until that decision is made, and the proper `STOMPOperationBinding` definition created. 

As for similarity, I think the implementation `amqp` might close? You'd be replacing `RabbitListener` with `MessageMapping`, the only nuisance is `SendTo` and `SendToUser` aren't properties of that Annotation, but that doesn't look to be to hard to account for.

**Comment by linghengqian** [comment]
@stavshamir Can we upgrade the AsyncAPI Spec version to 2.4.0 now? Or an issue with a higher priority?👀

**Comment by stavshamir** [comment]
Hey guys, thanks for leading this! I will try to dive in to this issue later toady! @linghengqian we can upgrade, could you tell if there are breaking changes from 2.0.0?

**Comment by linghengqian** [comment]
> @linghengqian we can upgrade, could you tell if there are breaking changes from 2.0.0?

- Spec 2.0.0 was released on September 11, 2019, while AsyncAPI released Spec 2.1.0 in March 2021 after joining the Linux Foundation, which has since introduced several breaking updates. We can see an overview of breaking changes from 2.1.0 to 2.4.0 at https://www.asyncapi.com/blog?tags=Release+Notes and https://github.com/asyncapi/spec/releases/tag .

- But https://github.com/asyncapi/jasyncapi never seems to support Async Spec 1.x, I don't understand why we need to know about AsyncAPI Spec 2.0.0's breaking update compared to AsyncAPI Spec 1.x, the subtext is Maven Central Dependency on AsyncAPI Spec 1.x only ? 😳 Should I open a new issue at https://github.com/asyncapi/jasyncapi ? Reference https://mvnrepository.com/artifact/com.asyncapi/asyncapi-core

- ![Screenshot_2022-05-05-16-04-43-04_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/20187731/166884262-71a3e63d-6668-4198-b5a8-cd80757ef6bc.jpg)

**Comment by Crain-32** [comment]
Oh sweet, I didn't find `jasyncapi`, that will be a help.

@stavshamir I tried the Discord Link the other day from the README, it looks like it has expired. Beyond that this actually mirrors [Issue 24](https://github.com/springwolf/springwolf-core/issues/24). Do you want to keep conversation on this Issue, or migrate it to that Issue and close this one?

**Comment by linghengqian** [comment]
- Maybe it would be better to go back to #24? However, the title of #24 needs to be changed; it actually refers to STOMP support. (I really don't see anyone introducing Spring WebSocket without using additional messaging protocols to extend message payloads)

**Comment by stavshamir** [comment]
@Crain-32 I fixed the invite link, it should work now.
@linghengqian I also agree about moving this to #24 - I will close this issue, and provide a list of tasks that we need to complete to implement this feature.
