### ISSUE TITLE
Example in Channel Headers is not shown correctly

### ISSUE THREAD

**Issue by timonback** [springwolf/springwolf-core#613]
**Describe the bug**
Visit https://demo.springwolf.dev/springwolf-ui/asyncapi-ui.html#channel-kafka-topic-defined-via-asyncPublisher-annotation-send-NestedPayloadDto and scroll down to the example box, which shows `null`

Expected: a json object with all fields (cloudevents in this case):
```json
{
            "__TypeId__": "io.github.stavshamir.springwolf.example.kafka.dtos.NestedPayloadDto",
            "ce_id": "2c60089e-6f39-459d-8ced-2d6df7e4c03a",
            "ce_source": "http://localhost",
            "ce_specversion": "1.0",
            "ce_subject": "Springwolf example project - Kafka",
            "ce_time": "2023-10-28 20:01:23+00:00",
            "ce_type": "NestedPayloadDto.v1",
            "content-type": "application/json"
          }
```

**Dependencies and versions used**
0.18.0 (latest)

**Code example**
The asyncapi.json file does contain the `examples`.
Checking the `asyncapi-mapper.service.ts` is probably a good start.

**Stack trace and error logs**

**Comment by raphaeldelio** [comment]
Hey Timon! Can I pick up this one?

**Comment by raphaeldelio** [comment]
Just saw its already done 😄
