### ISSUE TITLE
Add multi message support for AMQP producers and consumers

### ISSUE THREAD

**Issue by hirth-abi** [springwolf/springwolf-core#64]
1. Support for multiple messages per producers was added in #59 for Kafka. Such support should be also added for AMQP.

2. At least for AMQP multiple messages per consumer should be supported. This is available for Spring Boot with the `@RabbitListener` together with the `@RabbitHandler` annotation, see [documentation](https://docs.spring.io/spring-amqp/reference/html/amqp.html#annotation-method-selection).

**Comment by stavshamir** [comment]
I will probably provide this in the next amqp plugin release, thanks for reporting this.

**Comment by stavshamir** [comment]
We have low usage for amqp plugin, so we will not be able to invest time in this. If someone would like to try contributing an implementation, please let us know. Closing for now.

**Comment by hirth-abi** [comment]
Hi @stavshamir since you have now deprecated AsyncApiDocket, which was our only way to work around this missing support (and we currently don't have resources to contribute this implementation), does this mean you want to just cut off those users and we have to freeze our usage at least to the last version where AsyncApiDocket is supported?

**Comment by stavshamir** [comment]
@timonback may be able to help. I believe one of the new additions to configuration may be able to solve your issue. You are also welcome to the [discord server](https://discord.gg/W7ZZwy9f) if it's more convenient.

**Comment by timonback** [comment]
Hi @hirth-abi 
Thank you for the report as this helps us to understand which features are being used.

Our assumption is that all features of the AsyncApiDocket are available via other mechanisms as well.

You are talking about the producer configuration, right? The idea is to migrate towards an annotation based approach as documented here: https://www.springwolf.dev/docs/configuration/documenting-producers
When two producer (or consumer) methods specify the same channelName, then those are merged together. This allows to define multiple payloads for the same topic.

Does this solve your issue? If not, please open a new issue as closed issues are difficult to see for us.

**Comment by timonback** [comment]
@hirth-abi Feel free to add more info in #445
