### ISSUE TITLE
XML Examples for Arrays/Lists are missing the list-item-element

### ISSUE THREAD

**Issue by sam0r040** [springwolf/springwolf-core#642]
**Describe the bug**
Given the following class definition
```java
@XmlRootElement(name = "ArrayFoo")
private static class ArrayFoo {
    private List<SimpleFoo> fList;
}
```
The following example should be generated:
```xml
<ArrayFoo>
    <flist>
        <SimpleFoo>
            <b>true</b>
            <s>string</s>
        </SimpleFoo>
    </flist>
</ArrayFoo>
```
But currently the following example is generated:
```xml
<ArrayFoo>
    <flist>
        <b>true</b>
        <s>string</s>
    </flist>
</ArrayFoo>
```

**Dependencies and versions used**
1.0.0
**Code example**
If possible, an example project or snippet that reproduces the bug.

**Stack trace and error logs**
If an exception has been thrown or an error was logged by springwolf.

**Comment by timonback** [comment]
Thank you for the report, the issue has been addressed in the new release.

Feel free to reopen this issue if there is still something missing.
