### ISSUE TITLE
Not able to define headers in request without schema

### ISSUE THREAD

**Issue by victorlev01** [springwolf/springwolf-core#650]
Problem - no schema for headers (HeadersNotDocumented) defined in Kafka Listeners.
As we have many listeners like this, for user there is no way to test them.

**Dependencies and versions used**
    implementation 'io.github.springwolf:springwolf-kafka:1.0.0'
    implementation 'io.github.springwolf:springwolf-ui:1.0.0'

**Code example**
Workaround used around this issue:

`@Component
public class CustomAsyncApiCustomizer implements AsyncApiCustomizer {

    @Override
    public void customize(AsyncAPI asyncAPI) {
                var components = asyncAPI.getComponents();
                var notDocumentedHeaders = components.getSchemas().get("HeadersNotDocumented");
                notDocumentedHeaders.setType("object");
                var exampleHeader = new HashMap<String, String>();
                exampleHeader.put("key", "value");
                notDocumentedHeaders.setExamples(List.of(exampleHeader));`

**Stack trace and error logs**
No errors, just missing user experience

Created pr changing default ui behavior - hiding headers without schema or examples
https://github.com/springwolf/springwolf-core/pull/649

**Comment by timonback** [comment]
Thank you @victorlev01 for the feature request and contribution.
It has just been released.
