### ISSUE TITLE
Missing schemaSetting in case of googlepubsub protocol

### ISSUE THREAD

**Issue by SheheryarAamir** [springwolf/springwolf-core#651]
**Describe the bug**
When using googlepubsub as protocol using version 1.0.0 generated asynapi(3.0.0) docs does not add `schemaSetting` under bindings->googlepubsub, which is required for passing asynapi(3.0.0) validation. 

**Dependencies and versions used**
spring-wolf v1.0.0 (CloudStream)

**Code example**
After some initial investigation I found out that class `CloudStreamFunctionChannelsScanner` in method `buildMessageBinding` always map `EmptyMessageBinding` which is wrong.

**Stack trace and error logs**
`googlepubsub` property must have required property `schemaSettings`

**Comment by timonback** [comment]
Thank you @SheheryarAamir for the feature request and contribution, it has been published now.

We highly appreciate if you spare some minutes to update the documentation as you have the knowledge of the google pubsub bindings, for example here: https://github.com/springwolf/springwolf.github.io/blob/master/docs/configuration/documenting-bindings.md
