### ISSUE TITLE
Add support for custom Model Converters

### ISSUE THREAD

**Issue by yasen-pavlov** [springwolf/springwolf-core#70]
Having the ability to register custom model converters would be quite useful. 

I ran into this issue because we are using MonetaryAmount in our POJOs and it breaks the schema generation.  There was a similar issue in springdoc that was solved this way: springdoc/springdoc-openapi#606

As per our great discussion on discord, the best way to approach this is to add the ability to register new model converters in the core package and then to create a module that contains common model converters like the one for Monetary Amount to avoid bloating the core with unnecessary dependencies. 

Thank you very much for the great work @stavshamir.

**Comment by stavshamir** [comment]
These are the things should add:
(1)  `DefaultSchemaService` should be injected with a list of `ModelConverter` beans and add them to the `ModelConverters` instance. This alone will allow users to register their own model converters. It would also be nice to have an example of this in the example projects.
(2) Create new common model converters module for problematic classes like `MonetaryAmount` that will declare model converters beans and that's it. See springdoc's custom model converters.

I will create the new module structure. but you can already start implementing (1). Thanks!

**Comment by stavshamir** [comment]
Current tasks for the new `springwolf-common-model-converters` module:
- [ ] Add some info in the README file
- [ ] Add github workflow file (I will do it)
- [ ] Add the model converters + tests
