### ISSUE TITLE
Polymorphism support for kotlinx.serialization

### ISSUE THREAD

**Issue by geirsagberg** [springwolf/springwolf-core#707]
**Describe the feature request**
Given a polymorphic hierarchy like this:

```kotlin
@Serializable
sealed interface Event

@Serializable
@SerialName("PostAdded")
data class PostAdded(val message: String) : Event

@Serializable
@SerialName("PostDeleted")
data class PostDeleted(val id: Int): Event
```

I would expect the generated schema to contain a `oneOf: PostAdded, PostDeleted` for `Event`, along with a discriminator property, such as it does for Jackson.

**Motivation**
We have several events that used `sealed interface` and polymorphism. This maps cleanly to `oneOf` in OpenAPI and AsyncAPI, and should be supported.

**Comment by ctasada** [comment]
Hey @geirsagberg thanks for the report.

The support for Kotlin Serialization is still in Beta. PRs are welcome, but that's something that was already in my TODO

**Comment by ctasada** [comment]
Hey @geirsagberg,

I did a quick implementation that seems to work. Can you double-check that's properly working in your use case?

**Comment by geirsagberg** [comment]
Nice, code seems to do the job far as I can tell, however we went for gRPC and Armeria for docs in the end, instead of RabbitMQ, so I can't test it unfortunately. But kudos for the quick support, I'm sure I won't be the last seeking this 😊
