### ISSUE TITLE
Full package names in docs, new & how to avoid?

### ISSUE THREAD

**Issue by piewie** [springwolf/springwolf-core#742]
Hello,

We are busy bumping springwolf to 1.1.0 (from 0.5x) and we noticed that the objects are now full package named in the specification.

FE in demo on springwofl.dev we see 'io.github.springwolf.examples.kafka.dtos.NestedPayloadDto'

Can we avoid this somehow and only have 'NestedPayloadDto' in the yaml/json?

**Comment by timonback** [comment]
Hi @piewie,
Great that you are updating.

Have a look at the release notes: https://github.com/springwolf/springwolf-core/releases/tag/v1.0.0

You can use `use-fqn=false` to stick with simple class names 

Docs: https://www.springwolf.dev/docs/configuration/#additional-applicationproperties

**Comment by timonback** [comment]
"Required for publishing" refers to the springwolf-ui feature, where you can publish new messages through the ui.
