### ISSUE TITLE
Configurable URL in Springwolf UI

### ISSUE THREAD

**Issue by madrimas** [springwolf/springwolf-core#757]
It would be nice to have an option to configure custom URL for Springwolf UI. E.g.: `springwolf.ui.url=/custom/url`

Without the feature there is no option to use the UI in multi-services projects - the flagship example is k8s environment with many microservices based on the same baseUrl. So I want to have a possibility to configure UI url like that: `baseUrl + myMicroserviceId + ui.html`.

From my perspective the solution can be based on Swagger UI solution.

I don't know if any alternative will be sufficient, from my perspective is a missing key feature.

**Comment by madrimas** [comment]
Hi @sam0r040! Thanks for quick reply!

Something different. I want to set custom path without setting spring context path in whole app.
In swagger UI there is:
`springdoc.swagger-ui.path` - where you can set custom path, in my case `{myMicroserviceId} + custom-path`

then I can get swagger UI in my browser via such URL: `{someBaseUrl, eg. k8s cluster, or localhost} / {myMicroserviceId} / custom-path / swagger-ui / index.html`, e.g. `localhost/pet-service/custom-path/swagger-ui/index.html`

In Springwolf I want to configure it in the similar way, e.g.:
`springwolf.ui.url=/{myMicroserviceId}/custom-path/`

then I'll get Springwolf UI in my browser via such URL: `localhost/pet-service/custom-path/springwolf/asyncapi-ui.html` instead of `localhost/springwolf/asyncapi-ui.html`

So, as I said, it's similar case to context path, bout without setting it (due to some requirements, I cannot set context path in the whole app).

**Comment by madrimas** [comment]
so @sam0r040 how do you see that? Is there a possibility to add such feature?

**Comment by sam0r040** [comment]
Hi @madrimas, we are currently looking into this feature.

**Comment by madrimas** [comment]
Hi @sam0r040, that's great! I look forward to hearing more good news

**Comment by madrimas** [comment]
I've tested the snapshot, looks brilliant, thanks!

After release I'll check it once again and then close the issue.
