### ISSUE TITLE
Multiple RoutingKeys per Queue not supported? java.lang.IllegalStateException: Duplicate key

### ISSUE THREAD

**Issue by keydon** [springwolf/springwolf-core#79]
**Describe the bug**
The RabbitChannelsScanner seems not to support Queues with multiple RoutingKeys bound, which is funny :D

**Dependencies and versions used**
`springwolf-amqp` version `0.3.1`. (thows Exception)
`springwolf-amqp` version `0.2.0`. (ignores 2nd Binding)

**Code example**
One queue, two bindings.
```java
    @Bean
    @Qualifier("featured-list")
    public Queue featuredListQueue(@Value("${featured.items.list.queue}") String queue){
        return QueueBuilder.durable(queue).quorum().build();
    }

    @Bean
    public Binding bindfeaturedImplicit(@Qualifier("channel") Exchange channelExchange, @Qualifier("featured-list") Queue featuredListQueue){
        return BindingBuilder.bind(featuredListQueue).to(channelExchange).with("channel.listMy.rk").noargs();
    }

    @Bean
    public Binding bindfeaturedExplicit(@Qualifier("featured") Exchange featuredExchange,
                                        @Qualifier("featured-list") Queue featuredListQueue,
                                        @Value("${featured.items.list.rk}") String rk){
        return BindingBuilder.bind(featuredListQueue).to(featuredExchange).with(rk).noargs();
    }
```

**Stack trace and error logs**
If an exception has been thrown or an error was logged by springwolf.
```
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: 
	Error creating bean with name 'rabbitChannelsScanner' defined in URL [jar:file:/C:/Users/.../.m2/repository/io/github/springwolf/springwolf-amqp/0.3.1/springwolf-amqp-0.3.1.jar!/io/github/stavshamir/springwolf/asyncapi/scanners/channels/RabbitChannelsScanner.class]: ...
Caused by: org.springframework.beans.BeanInstantiationException: ...
Caused by: java.lang.IllegalStateException: 
	Duplicate key featured.items.list.queue (attempted merging values 
	Binding [destination=featured.items.list.queue, exchange=channel.exchange, routingKey=channel.listMy.rk, arguments={}] and
	Binding [destination=featured.items.list.queue, exchange=featured.exchange, routingKey=featured.items.list.rk, arguments={}])
```

**Comment by stavshamir** [comment]
Thanks for the detailed issue, I will take a look

**Comment by stavshamir** [comment]
I see the problem, just want to ask about the expected results:
1. For a given channel (same exchange and queue), when given multiple bindings each with a different routing key, the operation binding field `cc` will be a list containing all the routing keys associated with that exchange and queue.
2. Given the same queue name on different exchanges, like in your example, each will have its own channel. Currently the channel name is the queue name, but that will have to change to "exchange-name/queue-name". The operation binding in this case will contain only the routing key associated with that specific channel.

Does that make sense? Please let me know if you have any thoughts, and if you'd like to talk about this further you can join the discord server https://discord.gg/HZYqd5RPTd

**Comment by keydon** [comment]
Hio, sorry for not getting back to you sooner. Thanks for looking into my issue.

Mhh I see it is not easy to represent AMQP/RabbitMQ with AsyncApi, since you are very free how to use it.

So if I understand the AsyncApi-Specs correctly, a channel is something that can receive or send messages.
So for me in the AMQP/RabbitMQ world, that would be a queue or a routingKey (or exchange/queue (or exchange/queue/routingkey)). (https://github.com/asyncapi/bindings/blob/master/amqp/README.md#channel)

For me personally and how I use rabbitmq the channel is just the routingKey. The other stuff is just "bindings".

For Events the routinkKey is the event and multiple services/queues listen on it.
For Commands the routingKey is the endpoint of a single service/single queue that processes it.
The exchange doesnt really matter to me at all, since in the end they all are bound to three "main"-exchanges.

So ideally, in my case I would get two channels (one per routingKey) with a bunch of bindings. But not sure if thats within the realm of possibility in the current spec.

But I am also fine with your suggestions, if my approach would break to many other ppls docs.

**Comment by stavshamir** [comment]
We have low usage for amqp plugin, so we will not be able to invest time in this. If someone would like to try contributing an implementation, please let us know. Closing for now.
