### ISSUE TITLE
Allow for declaration of multiple co-existing AsyncAPIs

### ISSUE THREAD

**Issue by Sheldoras** [springwolf/springwolf-core#805]
**Describe the feature request**
Currently Springwolf only allows for one AsyncAPI document to be provided by a service. The only limiting option about 'which' channels/operations etc go into said AsyncAPI specification is the `base-package` property.

Looking at other tools (Springdoc for OpenAPI spec generation for example) they allow for multiple OpenAPI specs to be declared in parallel (say one spec for version 1.0.0 and one for 2.0.0 which are simultaneously supported by a service). It is also possible to filter more finely which endpoints (in the case of OpenAPI) go into which OpenAPI specification.

**Motivation**
If a service wants to support different AsyncAPI versions in parallel, it would be beneficial if two (or more) distinct specifications could be configured, each including only its relevant channels/operations/schemas.

**Technical details**
With Springdoc and OpenAPI this declaration can look like so:
```java
    @Bean
    fun version1(): GroupedOpenApi {
        val version = "1.0"
        return GroupedOpenApi.builder()
            .group(version)
            .displayName("API Version $version")
            .pathsToMatch("/public/v1/**")
            .pathsToMatch("/legacy/v1/**")
            .build()
    }

    @Bean
    fun version2(): GroupedOpenApi {
        val version = "2.0"
        return GroupedOpenApi.builder()
            .group(version)
            .displayName("API Version $version")
            .pathsToMatch("/public/v2/**")
            .pathsToMatch("/legacy/v2/**")
            .pathsToExclude("/public/v2/secret/**")
            .build()
    }
```

Something equivalent for providing multiple AsyncAPI specifications per service would be fantastic

**Comment by timonback** [comment]
Hi @Sheldoras,

Great suggestion.


A couple questions for understanding:
1. How do you plan to group the different endpoints (`pathsToMatch` in OpenAPI)? Is it only based on the channel name or do you actually intend to group by the actual operation (including the schema, so that you can differentiate between v1 and v2 payloads)?
2. Have you considered tags within the current document?
3. Do you wish to group into different documents (`group` in OpenAPI)?

**Comment by timonback** [comment]
Hi @Sheldoras ,
we just merged a first preview of this feature. It is available as a SNAPSHOT.

The group can be configured in `application.properties` (example: https://github.com/springwolf/springwolf-core/blob/master/springwolf-examples/springwolf-kafka-example/src/main/resources/application.properties#L43).

More details about the configuration at https://github.com/springwolf/springwolf-core/blob/master/springwolf-core/src/main/java/io/github/springwolf/core/configuration/properties/SpringwolfConfigProperties.java#L202 (only one of the filters (regex pattern) can be used)

Also, the group can be selected as part of the ui via settings button in the header.

---

Does this address your use-case? What is still missing?

We are looking forward to your feedback.

**Comment by timonback** [comment]
Hi @Sheldoras, awesome!

Grouping is a feature that can develop a high complexity quickly while requiring stable apis. This is the reason we went with property based configuration first.

To understand further, do you declare group dynamically or dynamically modify a grouped AsyncApi? I could imagine a group specific AsyncAPI customizer as a public interface - in addition to the current interface.

**Comment by Sheldoras** [comment]
Hello @timonback !
The groups and their versions are hardcoded and don't change dynamically at runtime. 
So the properties setup would work for us (it's then just unfortunately inconsistent with the way we define our OpenAPI groups - which is happening as shown in the code snippet in my last post, so programatically).

What the current solution lacks that we would need is the ability to make these "arbitrary" changes to the spec (add extension fields, change the version field etc). So any possibility, as the one you already mentioned, to make group-specific adjustments to the spec would work for us!

Thanks!

**Comment by timonback** [comment]
Hi @Sheldoras,
for the beginning we chose the easy option of allowing to overwrite the `info` object per group (instead of beans or adding a customizer).

We are still working on it (https://github.com/springwolf/springwolf-core/pull/1093), but here is the preview:

```properties
springwolf.docket.group-configs[0].group=Only Vehicles
springwolf.docket.group-configs[0].info.description=This group only contains endpoints that are related to vehicles.
springwolf.docket.group-configs[0].info.extension-fields.x-apitype=internal
```

Does this solve your request:
> What the current solution lacks that we would need is the ability to make these "arbitrary" changes to the spec (add extension fields, change the version field etc).

**Comment by Sheldoras** [comment]
Hi @timonback,
thanks for your work! Yes that would solve our current need for flexibility with the info object per group! :)
