### ISSUE TITLE
Payload schema is not documented in a batch kafka listener 

### ISSUE THREAD

**Issue by bdridi** [springwolf/springwolf-core#87]
**Describe the bug**

For a Kafka batch listener where a the type  of the the parameter of the listener method is `List<ExamplePayload>`, the schema of `ExamplePayload` is not documented. The consumer is displayed with a schema : `java.util.List` 
 
**Dependencies and versions used**

For example, `springwolf-kafka` version `0.7.0

**Code example**

```kotlin
 @KafkaListener(
        topics = ["topic-example"],
        containerFactory = "ExamplePayloadKafkaListenerContainerFactory"
    )
    fun examplePayloadBatchListener(examplePayloadList: List<ExamplePayload?>) {
        // ...
    }
```

**Comment by stavshamir** [comment]
Since type erasure it is challenging to get the type parameters at run time. I guess there are ways to overcome this, but the solution is usually on the client side - to have a class wrapping the generic type. 

If you can come up with a better solution please let me know.

**Comment by stavshamir** [comment]
Done thanks to @timonback . Will be available in the next release.
