### ISSUE TITLE
📍 META: Redesign `springwolf-ui`: Feedback, Discussion & Participation

### ISSUE THREAD

**Issue by timonback** [springwolf/springwolf-core#872]
# `springwolf-ui` is getting a new design, share your feedback and participate.

Check the latest demo at https://demo.springwolf.dev (by clicking the feature toggle in the toolbar header)

## How to code
1. Clone this repository and go to the `springwolf-ui` folder
2. Install dependencies: `npm ci`
3. Start the ui: `npm start`
4. The ui is ready at `http://localhost:4200` - including live refresh
5. Start changing code, i.e. the new sidebar is at `springwolf-ui/src/app/components/new/sidenav`

**Comment by hirth-abi** [comment]
I think the new UI is very nice for quick navigation. What's mainly lacking is IMHO the very "clean/tidy" look of the old one. We are using it also to communicate with non-developer stakeholders, where this is not unimportant 😉 

For example the current sidebar 

<img width="289" alt="SCR-20240802-noz" src="https://github.com/user-attachments/assets/57278847-4cad-4613-b0e5-4f385d882342">

in comparison to something like (spacing, auto-width, no line breaks, icon alignment)

<img width="334" alt="SCR-20240802-npl" src="https://github.com/user-attachments/assets/84384693-b6e0-47dd-8de5-8e420d837cbc">

**Comment by timonback** [comment]
Thank you @hirth-abi for the feedback.
I see the improvements in the second screenshot. In case these were code changes, do you mind putting them on an branch and opening a PR? i.e. the styling for the sidenav is located at `springwolf-ui/src/app/components/new/sidenav`

Regarding your users and stakeholders: you do you mainly think about spacing, etc. (clean/tidy) as in the sidebar or also a different way to present the information?

**Comment by hirth-abi** [comment]
I've just hacked the changes in https://github.com/hirth-abi/springwolf-core/tree/css-playground but those are probably not clean and the auto-width does not really work, since I have too little CSS experience currently.

What would be also nice - _for our way we use it_ - is a possibility to hide unused/empty sections. In the old UI the operation bindings were not visible by default (tab) which we don't use, and some information is basically clutter:
- message binding is not used
- content-type is always application/json, so redundant at each message
- server is always the same, so redundant at each message

**Comment by timonback** [comment]
Sure @hirth-abi, can you open an _enhancement_ issue for this feature request?

You are also very welcome to contribute this feature. Initial thought regarding implementation is a new endpoint that returns (validated) configuration (`application.properties` is mapped by Spring into `SpringwolfConfigProperties.java`). The ui queries the new endpoint - similar like the publishing functionality and shows/hides the parts in the ui.

**Comment by timonback** [comment]
@hirth-abi I opened an enhanchement issue in https://github.com/springwolf/springwolf-core/issues/1001 for your request.

---
As the ui is available for some time and the default now, I close this issue.

For any feature requests/issues/contributions/etc, please open a new issue
