### ISSUE TITLE
Header definitions are overriding others

### ISSUE THREAD

**Issue by hirth-abi** [springwolf/springwolf-core#893]
**Describe the bug**

When multiple `@AsyncOperation`s with `@Headers` are defined, only one of them will be used for all.

Se my reproducer project where different header values should be shown:

<img width="1042" alt="SCR-20240802-jif" src="https://github.com/user-attachments/assets/dbe7082d-addd-4de2-bf40-23fa2cc4356e">

Additionally in the old UI a strange schema with "undefined-title" is shown for it:

<img width="832" alt="SCR-20240802-jje" src="https://github.com/user-attachments/assets/e75b4e76-73f7-4def-91dc-b76ad09a2b96">

**Dependencies and versions used**

Tested in 1.5.0

**Code example**

https://github.com/springwolf/springwolf-core/compare/master...hirth-abi:springwolf-core:header-override

**Stack trace and error logs**
-

**Comment by timonback** [comment]
Hi @hirth-abi,
have you tried adding the `schemaName` in AsyncOperation.Headers?
(Validation for the field is added in #896 )

**Comment by hirth-abi** [comment]
Yes, that works if the schema is different and defining the header name in a meaningful non-generated way seems to be better 👍  (it just looks a bit strange - although technically correct - to have a different header schema per message, just because the same standardized header is sent with a different value)
