### ISSUE TITLE
Add code formatter (java/angular)

### ISSUE THREAD

**Issue by timonback** [springwolf/springwolf-core#93]
As a contributor, I face the difficulty of learning the project specific style guide.
I personally, like the approach to use a formatter, which applies the format to keep the project in a consistent style. Also, I do not have to think (as much) about formatting anymore. Running a gradle task should fix most intendation, line breaks, syntax issues.

In the past, I have used https://github.com/diffplug/spotless, which has IDE + gradle integration and formatting options for many languages, including java and typescript. I used Java/Eclipse and npm/prettier.

@stavshamir What do you think about integrating a code formatter? Do you have a preferred style?

**Comment by stavshamir** [comment]
I never used a formatter in Java, but I see your point and it is probably more important in open source projects where contributions may be sporadic and come from people with different backgrounds. I will look into this tool and other alternatives.
Thanks for the suggestion

**Comment by stavshamir** [comment]
@timonback I skimmed through the spotless link you provided, and it looks nice, especially if you already used it. Let's go for it! As for the specific styles - I think we should try and stick with the current style as much as possible, but as always I'm open to changes.

If you take this, please attach here a preview of the intended changes before implementation so we can discuss them.

**Comment by timonback** [comment]
I have created a draft PR here: https://github.com/springwolf/springwolf-core/pull/140

Let's discuss what feel feasible. spotless is quite straigh-forward to use. If you want to try it, you can change the configuration in build.gradle and run the spotlessApply task and it will reformat the files - without manual work
