### ISSUE TITLE
Add support for kafka headers

### ISSUE THREAD

**Issue by timonback** [springwolf/springwolf-core#94]
Springwolf already provides documentation for the data payload. Transport metadata (aka headers) cannot be documented with springwolf at this point.
Why the separation? The data/domain payload should be separate from the transport metadata. In REST APIs, the HTTP Content-Type, Content-Length is also a header and (usually) not part of the response object.

AsyncApi allows to define headers as part of the message, similar as the payload is defined: https://www.asyncapi.com/docs/reference/specification/v2.4.0#messageObject

Personal use-case:
https://cloudevents.io is an upcoming standardization, which relies on putting metadata into headers. I would like to document those headers. I do not intend to create any kind of dependency on cloudevents.

**Comment by stavshamir** [comment]
See #86

**Comment by sam0r040** [comment]
Just to keep everything together, the issue that triggered me for PR https://github.com/springwolf/springwolf-core/pull/86 : Issue https://github.com/springwolf/springwolf-core/issues/51

**Comment by timonback** [comment]
By reading #51, I was not sure if documenting the headers is part of it, or only making the springwolf-ui produce to topic functionality work.
If documenting the headers as part of springwolf-ui is part of it, this is a duplicate and can be closed.

**Comment by stavshamir** [comment]
That's a good point, I was just commenting about it in #51. @sam0r040 in his PR only provides a fix for producing to a topic which has multiple payload types, so let's leave this one (maybe describe it with more detail).
