### ISSUE TITLE
Schema on UI is not Displaying as expected

### ISSUE THREAD

**Issue by 19941112** [springwolf/springwolf-core#98]
**Describe the bug**
after updating the versions of spring wolf from 0.1.0  to 0.4.0 and spring wolf-ui from 0.3.1 to 0.5.0 on spring UI page schema tabs are not displaying as expected.

**Dependencies and versions used**
springwolf-amqp - 0.4.0
springwolf-ui - 0.5.0.

**Code example**
below attached the code snippet and output which is displayed on the UI page
![image](https://user-images.githubusercontent.com/50715301/192711960-e49d4ad2-e72c-4e8d-90e1-61d7372ae28e.png)
![image](https://user-images.githubusercontent.com/50715301/192712854-51ac64a0-050d-4622-8b7d-1bb14cf69548.png)

**Comment by timonback** [comment]
Hi @19941112 , thank you for the report.
Can you further specify what you are expecting?

Based on the screenshots provided, there is an amqp producer queue which produces the `OrderStatus` schema. As part of the schema tab, three fields are listed. One of them is `Order`.
In the Schemas section in the UI, only one schema can be expanded at the same time, which is `Order` at this point. If you expand `OrderStatus`, I assume that you can see the same three fields as in the `OrderStatus` tab.

**Comment by 19941112** [comment]
in the older versions I see the schema tab is displaying as below 
![image](https://user-images.githubusercontent.com/50715301/193520301-30852d7f-d2a5-4be9-8037-a55aac04cc9a.png)

**Comment by stavshamir** [comment]
Hi @19941112, this is the intended behavior. The new UI schema display is more inline with other open api and async api UIs.
